### ISSUE TITLE
 oracle_response_time Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `不支持这个指标`

### ISSUE THREAD

**Issue by runner-mei** [three-plus-three/hw_issues#101]
[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `不支持这个指标`
[error] application - Failed to get value of metric[oracle_response_time] for mo[service_database][1170]
java.lang.RuntimeException: 不支持这个指标
	at lib.rest.Base$class.sendRequest(Base.scala:129) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Base$class.getJSON(Base.scala:28) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at helpers.ServiceHelper$.getValueJson(ServiceHelper.scala:1767) [tpt_web.tpt_web-2.2.jar:2.2]

**Comment by runner-mei** [comment]
改成 db_response_time

**Comment by eeiceyes** [comment]
fixed
