### ISSUE TITLE
com.alibaba.fastjson.JSONException: syntax error, expect [, actual {, pos 0

### ISSUE THREAD

**Issue by runner-mei** [three-plus-three/hw_issues#103]
这个错误，能打印批标名不？

[error] application - Failed to parse json `{"FREE":1.063256064E+10,"DESTINATION":"USE_DB_RECOVERY_FILE_DEST","TOTAL":1.073741824E+10,"DEST_NAME":"LOG_ARCHIVE_DEST_1","USED":1.048576E+8}`
com.alibaba.fastjson.JSONException: syntax error, expect [, actual {, pos 0
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:1014) ~[com.alibaba.fastjson-1.2.4.jar:na]
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:1001) ~[com.alibaba.fastjson-1.2.4.jar:na]
	at com.alibaba.fastjson.JSON.parseArray(JSON.java:323) ~[com.alibaba.fastjson-1.2.4.jar:na]
	at helpers.ServiceHelper$$anonfun$resolveOracleArchiveStat$1.apply$mcV$sp(ServiceHelper.scala:1412) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at helpers.ServiceHelper$.safeResolve(ServiceHelper.scala:1740) [tpt_web.tpt_web-2.2.jar:2.2]

**Comment by eeiceyes** [comment]
fixed
