### ISSUE TITLE
[登入]平台登入后报错

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1506]
平台输入账号密码后报错

Caused by: java.lang.RuntimeException: {"message":"验证 ticket 失败 - code=401, message=service ticket isn't found"}
	at lib.rest.Base$class.sendRequest(Base.scala:137) ~[tpt_web.tpt_web-3.2.1.jar:3.2.1]
	at lib.rest.Base$class.getJSON(Base.scala:27) ~[tpt_web.tpt_web-3.2.1.jar:3.2.1]
	at lib.rest.Systems$.getJSON(Systems.scala:11) ~[tpt_web.tpt_web-3.2.1.jar:3.2.1]
	at lib.rest.Systems$.checkTicket(Systems.scala:38) ~[tpt_web.tpt_web-3.2.1.jar:3.2.1]
	at controllers.LoginController$$anonfun$loginBySSO$1.apply(LoginController.scala:69) ~[tpt_web.tpt_web-3.2.1.jar:3.2.1]
	at controllers.LoginController$$anonfun$loginBySSO$1.apply(LoginController.scala:66) ~[tpt_web.tpt_web-3.2.1.jar:3.2.1]
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:433) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:432) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.mvc.Action$.invokeBlock(Action.scala:556) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.mvc.Action$.invokeBlock(Action.scala:555) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:518) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.11.1.jar:na]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:705) ~[com.typesafe.play.play-iteratees_2.11-2.3.9.jar:2.3.9]
	at play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:705) ~[com.typesafe.play.play-iteratees_2.11-2.3.9.jar:2.3.9]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[org.scala-lang.scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[org.scala-lang.scala-library-2.11.1.jar:na]
	... 6 common frames omitted

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170901_2692_x64.exe 版本确认，close处理。
