### ISSUE TITLE
[组合告警]禁用启用组合告警规则出错

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1531]
1.禁用启用组合告警规则出错
2.现象只做出来过一次

[server_biz.txt](https://github.com/three-plus-three/hw_issues/files/1291438/server_biz.txt)
[web_server.txt](https://github.com/three-plus-three/hw_issues/files/1291439/web_server.txt)

**Comment by runner-mei** [comment]
z.rest.resources.composited_alert.CompositedAlertResource - Updating composited_alert!
2017-09-11 11:27:38,984-[TS] ERROR pool-9-thread-6800 com.tpt.nm.biz.Errors - Throw unknown exception
java.lang.NullPointerException
	at com.tpt.nm.biz.rest.resources.composited_alert.CompositedAlertResource.updateCompositedAlert(CompositedAlertResource.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)


----------------------------------------------------


ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: {"errorCode": 100001, "errorMessage": "Unknown Exception"}
	at com.tpt.nm.biz.Errors.rethrowUnknownException(Errors.java:109)
	at com.tpt.nm.biz.rest.resources.composited_alert.CompositedAlertResource.updateCompositedAlert(CompositedAlertResource.java:136)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by eeiceyes** [comment]
暂时为重现
