### ISSUE TITLE
3.3 版本出错了

### ISSUE THREAD

**Issue by runner-mei** [three-plus-three/hw_issues#1616]
````








Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.postgresql.util.PSQLException: ERROR: syntax error at end of input
  位置：91
### The error may exist in com/tpt/nm/biz/system/dao/HengweiMapper.xml
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: select permission_object from hengwei_permissions_and_groups where type=1 and  group_id in
### Cause: org.postgresql.util.PSQLException: ERROR: syntax error at end of input
  位置：91
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:26)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:111)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:102)
	at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.session.SqlSessionManager$SqlSessionInterceptor.invoke(SqlSessionManager.java:285)
	at com.sun.proxy.$Proxy64.selectList(Unknown Source)
	at org.apache.ibatis.session.SqlSessionManager.selectList(SqlSessionManager.java:174)
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:119)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:63)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:52)
	at com.sun.proxy.$Proxy81.getPermissionTags(Unknown Source)
	at com.tpt.nm.biz.system.service.impl.HengweiAuthorizationGetter.getAuthorizedDevices(HengweiAuthorizationGetter.java:48)
	at com.tpt.nm.biz.rest.resources.ResourceBase.getAuthorizedDevices(ResourceBase.java:48)
	at com.tpt.nm.biz.rest.resources.alert.AlertEventCountResource.getVisibleMoIds(AlertEventCountResource.java:90)
	at com.tpt.nm.biz.rest.resources.alert.AlertEventCountResource.summaryLevelCount(AlertEventCountResource.java:70)
	at com.tpt.nm.biz.rest.resources.alert.AlertEventCountResource.getCount(AlertEventCountResource.java:49)
	at sun.reflect.GeneratedMethodAccessor178.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:137)
	... 17 more

````

**Comment by runner-mei** [comment]
fixed
