### ISSUE TITLE
[安装]平台安装后tpt_mc进程重启

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1693]
1.平台安装后tpt_mc进程重启

java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.tpt.nm.biz.guice.BizModule.invokeIt(BizModule.java:138)
	at com.tpt.nm.biz.guice.BizModule.startIt(BizModule.java:122)
	at com.tpt.nm.biz.guice.BizModule.startInstance(BizModule.java:496)
	at com.tpt.nm.biz.guice.BizModule.start(BizModule.java:484)
	at com.tpt.nm.Server.installGuice(Server.java:108)
	at com.tpt.nm.Server.main(Server.java:60)
Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: org.postgresql.util.PSQLException: 错误: 重复键违反唯一约束"hengwei_users_name_key"
  详细：键值"(name)=(admin)" 已经存在
### Cause: org.postgresql.util.PSQLException: 错误: 重复键违反唯一约束"hengwei_users_name_key"
  详细：键值"(name)=(admin)" 已经存在
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:26)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:154)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.session.SqlSessionManager$SqlSessionInterceptor.invoke(SqlSessionManager.java:278)
	at com.sun.proxy.$Proxy64.insert(Unknown Source)
	at org.apache.ibatis.session.SqlSessionManager.insert(SqlSessionManager.java:198)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:51)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:52)
	at com.sun.proxy.$Proxy71.createUser(Unknown Source)
	at com.tpt.nm.biz.system.service.impl.UserMigrate.migrate(UserMigrate.java:52)
	at com.tpt.nm.biz.system.service.impl.SystemManager.start(SystemManager.java:60)
	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:101)
	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:101)
	... 10 more

**Comment by eeiceyes** [comment]
fixed
