### ISSUE TITLE
HP-UNIX系统进程在运行视图中无法获取

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#172]
HP-UNIX在运行视图上获取不到进程列表
LOG：

[logs.zip](https://github.com/three-plus-three/hw_issues/files/150325/logs.zip)

**Comment by runner-mei** [comment]
! @6p8l14mi4 - Internal server error, for (GET) [/hengwei/service_hosts/2298/processes_table_for_snmp?random_ts=1456478829939&screen_width=1600&screen_height=860] ->

play.api.Application$$anon$1: Execution exception[[RuntimeException: 发生多个错误]]
	at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.11.1.jar:na]
Caused by: java.lang.RuntimeException: 发生多个错误
	at lib.rest.Base$class.sendRequest(Base.scala:129) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Base$class.getJSON(Base.scala:28) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at controllers.HostController$$anonfun$viewProcessesTableForSnmp$1.apply(HostController.scala:249) ~[tpt_web.tpt_web-2.2.jar:2.2]
[error] application - Server exception happened
play.api.Application$$anon$1: Execution exception[[RuntimeException: 发生多个错误]]
	at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.11.1.jar:na]
Caused by: java.lang.RuntimeException: 发生多个错误
	at lib.rest.Base$class.sendRequest(Base.scala:129) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Base$class.getJSON(Base.scala:28) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at controllers.HostController$$anonfun$viewProcessesTableForSnmp$1.apply(HostController.scala:249) ~[tpt_web.tpt_web-2.2.jar:2.2]

**Comment by runner-mei** [comment]
fix by #175

**Comment by Cuic** [comment]
HP-UNIX进程无法获取（运转视图进程信息）
华力FA环境；进程数较多（200多个进程）；通过添加进程监控告警可以获取进程信息；获取进程信息超时...

**Comment by runner-mei** [comment]
可能已经解决
