### ISSUE TITLE
com.tpt.nm.share.jedis.EventManager - java.util.NoSuchElementException: No value present

### ISSUE THREAD

**Issue by runner-mei** [three-plus-three/hw_issues#175]
````
2016-02-26 17:30:51,924-[TS] ERROR RedisQueuemetrics_arrive com.tpt.nm.share.jedis.EventManager - java.util.NoSuchElementException: No value present
java.lang.RuntimeException: java.util.NoSuchElementException: No value present
	at com.tpt.nm.share.eventbus.EventBus.post(EventBus.java:270)
	at com.tpt.nm.biz.mos.service.impl.MeasurementManager.onEvent(MeasurementManager.java:281)
	at com.tpt.nm.share.jedis.JedisEventManager$JedisPubSubClient.onMessage(JedisEventManager.java:156)
	at redis.clients.jedis.JedisPubSub.process(JedisPubSub.java:129)
	at redis.clients.jedis.JedisPubSub.proceed(JedisPubSub.java:102)
	at redis.clients.jedis.Jedis.subscribe(Jedis.java:2496)
	at com.tpt.nm.share.jedis.JedisEventManager$JedisPubSubClient.run(JedisEventManager.java:120)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.NoSuchElementException: No value present
	at com.tpt.nm.Optional.get(Optional.java:113)
	at com.tpt.nm.biz.mos.service.ManagedObjectStatusMonitor.checkMoLabel(ManagedObjectStatusMonitor.java:289)
	at com.tpt.nm.biz.mos.service.impl.NetworkStatusMonitor.checkMoAppearance(NetworkStatusMonitor.java:190)
	at com.tpt.nm.biz.mos.service.impl.NetworkStatusMonitor.onMetricEventArrive(NetworkStatusMonitor.java:126)
	at com.tpt.nm.biz.mos.service.ManagedObjectStatusMonitor.listen(ManagedObjectStatusMonitor.java:82)
	at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.tpt.nm.share.eventbus.EventHandler.handleEvent(EventHandler.java:72)
	at com.tpt.nm.share.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
	at com.tpt.nm.share.eventbus.EventBus.dispatch(EventBus.java:318)
	at com.tpt.nm.share.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
	at com.tpt.nm.share.eventbus.EventBus.post(EventBus.java:268)
	... 7 more

````

**Comment by runner-mei** [comment]
已修复
