### ISSUE TITLE
java.lang.RuntimeException: 发生多个错误

### ISSUE THREAD

**Issue by runner-mei** [three-plus-three/hw_issues#176]
[error] application - Failed to get value of metric[vmstat_rate] for mo[service_host][2298]
java.lang.RuntimeException: 发生多个错误
	at lib.rest.Base$class.sendRequest(Base.scala:129) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Base$class.getJSON(Base.scala:28) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at helpers.ServiceHelper$.getValueJson(ServiceHelper.scala:1774) [tpt_web.tpt_web-2.2.jar:2.2]
[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `发生多个错误`

**Comment by runner-mei** [comment]
已修复
