### ISSUE TITLE
LINUX系统使用SSH获取不到数据（cpu/mem/sys）

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#190]
````
2016-03-10 17:54:45,039-[TS] ERROR pool-7-thread-19 com.tpt.nm.biz.rest.resources.managed_object.NetworkDevicePortFluxResource - Failed to get flux
{"errorCode": 500, "errorMessage": "managed_object with id was '28367' is not found,execute 'SELECT type, address, updated_at, oid, display_name, zh_name, domain_id, device_type, owner, description, full_name, id, created_at, engine_id, name, manufacturer, location FROM tpt_network_devices WHERE id = $1' failed,table 'Linux' is not a subclass of 'network_device'."}
	at com.tpt.nm.metrics.SamplingError.toException(SamplingError.java:50)
	at com.tpt.nm.metrics.ExchangeResponse.toObject(ExchangeResponse.java:112)
	at com.tpt.nm.metrics.ExchangeResult.toObject(ExchangeResult.java:178)
	at com.tpt.nm.biz.rest.resources.managed_object.NetworkDevicePortFluxResource.getFlux(NetworkDevicePortFluxResource.java:84)
	at sun.reflect.GeneratedMethodAccessor194.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:137)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:280)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:234)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:221)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:356)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:179)
	at org.jboss.resteasy.plugins.server.netty.RequestDispatcher.service(RequestDispatcher.java:81)
	at org.jboss.resteasy.plugins.server.netty.RequestHandler.messageReceived(RequestHandler.java:56)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:43)
	at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:67)
	at org.jboss.netty.handler.execution.OrderedMemoryAwareThreadPoolExecutor$ChildExecutor.run(OrderedMemoryAwareThreadPoolExecutor.java:314)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
````

**Comment by runner-mei** [comment]
设备的 type 字段 为什么是 大写的 Linux， 而不是小写 linux

**Comment by runner-mei** [comment]
已解决
