### ISSUE TITLE
左键菜单出不来

### ISSUE THREAD

**Issue by runner-mei** [three-plus-three/hw_issues#1952]
````

play.api.Application$$anon$1: Execution exception[[NumberFormatException: For input string: "12天7小时6分钟6秒"]]
	at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.11.1.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:316) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [org.scala-lang.scala-library-2.11.1.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [org.scala-lang.scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.11.1.jar:na]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [com.typesafe.play.play-iteratees_2.11-2.3.9.jar:2.3.9]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [org.scala-lang.scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [org.scala-lang.scala-library-2.11.1.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [org.scala-lang.scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [org.scala-lang.scala-library-2.11.1.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [org.scala-lang.scala-library-2.11.1.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [org.scala-lang.scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.11.1.jar:na]
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67) [com.typesafe.akka.akka-actor_2.11-2.3.4.jar:na]
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82) [com.typesafe.akka.akka-actor_2.11-2.3.4.jar:na]
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59) [com.typesafe.akka.akka-actor_2.11-2.3.4.jar:na]
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59) [com.typesafe.akka.akka-actor_2.11-2.3.4.jar:na]
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) [org.scala-lang.scala-library-2.11.1.jar:na]
	at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58) [com.typesafe.akka.akka-actor_2.11-2.3.4.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41) [com.typesafe.akka.akka-actor_2.11-2.3.4.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [com.typesafe.akka.akka-actor_2.11-2.3.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.11.1.jar:na]
Caused by: java.lang.NumberFormatException: For input string: "12天7小时6分钟6秒"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043) ~[na:1.8.0_102]
	at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122) ~[na:1.8.0_102]
	at java.lang.Float.parseFloat(Float.java:451) ~[na:1.8.0_102]
	at scala.collection.immutable.StringLike$class.toFloat(StringLike.scala:249) ~[org.scala-lang.scala-library-2.11.1.jar:na]
	at scala.collection.immutable.StringOps.toFloat(StringOps.scala:30) ~[org.scala-lang.scala-library-2.11.1.jar:na]
	at helpers.ApplicationHelper$.translateTimeSpan(ApplicationHelper.scala:967) ~[tpt_web.tpt_web-3.3.1.jar:3.3.1]
	at helpers.TopologyHelper$.resolveValue(TopologyHelper.scala:396) ~[tpt_web.tpt_web-3.3.1.jar:3.3.1]
	at views.html.network_topology.annotation$$anonfun$apply$1$$anonfun$apply$2.apply(annotation.template.scala:52) ~[tpt_web.tpt_web-3.3.1.jar:3.3.1]
	at views.html.network_topology.annotation$$anonfun$apply$1$$anonfun$apply$2.apply(annotation.template.scala:34) ~[tpt_web.tpt_web-3.3.1.jar:3.3.1]
	at play.twirl.api.TemplateMagic$.defining(TemplateMagic.scala:13) ~[com.typesafe.play.twirl-api_2.11-1.0.2.jar:1.0.2]
	at views.html.network_topology.annotation$$anonfun$apply$1.apply(annotation.template.scala:34) ~[tpt_web.tpt_web-3.3.1.jar:3.3.1]
	at views.html.network_topology.annotation$$anonfun$apply$1.apply(annotation.template.scala:29) ~[tpt_web.tpt_web-3.3.1.jar:3.3.1]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245) ~[org.scala-lang.scala-library-2.11.1.jar:na]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245) ~[org.scala-lang.scala-library-2.11.1.jar:na]
	at scala.collection.Iterator$class.foreach(Iterator.scala:743) ~[org.scala-lang.scala-library-2.11.1.jar:na]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1174) ~[org.scala-lang.scala-library-2.11.1.jar:na]
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) ~[org.scala-lang.scala-library-2.11.1.jar:na]
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54) ~[org.scala-lang.scala-library-2.11.1.jar:na]
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245) ~[org.scala-lang.scala-library-2.11.1.jar:na]
	at scala.collection.AbstractTraversable.map(Traversable.scala:104) ~[org.scala-lang.scala-library-2.11.1.jar:na]
	at views.html.network_topology.annotation$.apply(annotation.template.scala:29) ~[tpt_web.tpt_web-3.3.1.jar:3.3.1]
	at controllers.NetworkTopologyController$$anonfun$getAnnotation$1.apply(NetworkTopologyController.scala:419) ~[tpt_web.tpt_web-3.3.1.jar:3.3.1]
	at controllers.NetworkTopologyController$$anonfun$getAnnotation$1.apply(NetworkTopologyController.scala:418) ~[tpt_web.tpt_web-3.3.1.jar:3.3.1]
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:433) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:432) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.mvc.Action$.invokeBlock(Action.scala:556) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.mvc.Action$.invokeBlock(Action.scala:555) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:518) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.11.1.jar:na]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:705) ~[com.typesafe.play.play-iteratees_2.11-2.3.9.jar:2.3.9]
	at play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:705) ~[com.typesafe.play.play-iteratees_2.11-2.3.9.jar:2.3.9]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[org.scala-lang.scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[org.scala-lang.scala-library-2.11.1.jar:na]
	... 6 common frames omitted

````

**Comment by eeiceyes** [comment]
fixed
