### ISSUE TITLE
[设备管理]添加设备后、拓扑图上设备类型自动获取不到

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1967]
1.添加设备后、拓扑图上设备类型自动获取不到

2018-04-10 13:45:32,190-[TS] ERROR pool-3-thread-10 com.tpt.nm.biz.mos.service.impl.ManagedObjectSynchronizer - Failed to sync sys!
{"errorCode": 500, "errorMessage": "mo(2527) isn't found."}
	at com.tpt.nm.metrics.SamplingError.toException(SamplingError.java:50)
	at com.tpt.nm.metrics.ExchangeResponse.toObject(ExchangeResponse.java:113)
	at com.tpt.nm.metrics.ExchangeResult.toObject(ExchangeResult.java:248)
	at com.tpt.nm.biz.mos.service.impl.MetricBrowseManager.getMetricOfMo(MetricBrowseManager.java:63)
	at com.tpt.nm.biz.mos.service.impl.ManagedObjectSynchronizer.syncSysInfo(ManagedObjectSynchronizer.java:365)
	at com.tpt.nm.biz.mos.service.impl.ManagedObjectSynchronizer.syncDevice(ManagedObjectSynchronizer.java:252)
	at com.tpt.nm.biz.mos.service.impl.ManagedObjectSynchronizer.access$000(ManagedObjectSynchronizer.java:40)
	at com.tpt.nm.biz.mos.service.impl.ManagedObjectSynchronizer$2.run(ManagedObjectSynchronizer.java:115)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by runner-mei** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_3.3.1.20180411_3119_x64.exe  版本确认，close处理。
