### ISSUE TITLE
[网络视图]centos设备SSH取数方式、添加成功后无法获取数据

### ISSUE THREAD

**Issue by hengwei-test** [three-plus-three/hw_issues#1982]
1.centos设备SSH取数方式、添加成功后无法获取数据
2.需要手动修改设备类型

2018-04-12 16:23:41,099-[TS] INFO pool-3-thread-8 com.tpt.nm.biz.mos.service.impl.ManagedObjectSynchronizer - Begin to synchronize device `192.168.1.126`
2018-04-12 16:23:41,100-[TS] INFO pool-3-thread-8 com.tpt.nm.biz.mos.service.impl.ManagedObjectSynchronizer - Start to sync sys info!
2018-04-12 16:23:41,103-[TS] ERROR pool-3-thread-8 com.tpt.nm.biz.mos.service.impl.ManagedObjectSynchronizer - Failed to sync sys!
{"errorCode": 400102, "errorMessage": "snmp is missing."}
	at com.tpt.nm.metrics.SamplingError.toException(SamplingError.java:50)
	at com.tpt.nm.metrics.ExchangeResponse.toObject(ExchangeResponse.java:113)
	at com.tpt.nm.metrics.ExchangeResult.toObject(ExchangeResult.java:248)
	at com.tpt.nm.biz.mos.service.impl.MetricBrowseManager.getMetricOfMo(MetricBrowseManager.java:63)
	at com.tpt.nm.biz.mos.service.impl.ManagedObjectSynchronizer.setSysForHost(ManagedObjectSynchronizer.java:593)
	at com.tpt.nm.biz.mos.service.impl.ManagedObjectSynchronizer.syncSysInfo(ManagedObjectSynchronizer.java:424)
	at com.tpt.nm.biz.mos.service.impl.ManagedObjectSynchronizer.syncDevice(ManagedObjectSynchronizer.java:252)
	at com.tpt.nm.biz.mos.service.impl.ManagedObjectSynchronizer.access$000(ManagedObjectSynchronizer.java:40)
	at com.tpt.nm.biz.mos.service.impl.ManagedObjectSynchronizer$2.run(ManagedObjectSynchronizer.java:115)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2018-04-12 16:23:41,104-[TS] INFO pool-3-thread-8 com.tpt.nm.biz.mos.service.impl.ManagedObjectSynchronizer - Start to sync port info!
2018-04-12 16:23:51,482-[TS] INFO pool-9-thread-7644 com.tpt.nm.biz.alert.service.impl.AlertManager$$EnhancerByGuice$$2e1328f2 - Quering alerts with url `alert_cookies?limit=10000000&offset=0&order=id+asc&@confirm_user=[is]null&@triggered_at=%5B%3E%5D2018-04-12T15%3A38%3A08.578%2B08%3A00`

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
tpt-3.3.1.20180419.1380~eaf4d81.x86_64.rpm  版本确认，还是出现此问题


018-04-20 10:04:31,546-[TS] INFO pool-3-thread-1 com.tpt.nm.biz.mos.service.impl.ManagedObjectSynchronizer - Start to sync sys info!
2018-04-20 10:04:31,611-[TS] ERROR pool-3-thread-1 com.tpt.nm.biz.mos.service.impl.ManagedObjectSynchronizer - Failed to sync sys!
{"errorCode": 400102, "errorMessage": "snmp is missing."}
	at com.tpt.nm.metrics.SamplingError.toException(SamplingError.java:50)
	at com.tpt.nm.metrics.ExchangeResponse.toObject(ExchangeResponse.java:113)
	at com.tpt.nm.metrics.ExchangeResult.toObject(ExchangeResult.java:248)
	at com.tpt.nm.biz.mos.service.impl.MetricBrowseManager.getMetricOfMo(MetricBrowseManager.java:63)
	at com.tpt.nm.biz.mos.service.impl.ManagedObjectSynchronizer.setSysForHost(ManagedObjectSynchronizer.java:593)
	at com.tpt.nm.biz.mos.service.impl.ManagedObjectSynchronizer.syncSysInfo(ManagedObjectSynchronizer.java:424)
	at com.tpt.nm.biz.mos.service.impl.ManagedObjectSynchronizer.syncDevice(ManagedObjectSynchronizer.java:252)
	at com.tpt.nm.biz.mos.service.impl.ManagedObjectSynchronizer.access$000(ManagedObjectSynchronizer.java:40)
	at com.tpt.nm.biz.mos.service.impl.ManagedObjectSynchronizer$2.run(ManagedObjectSynchronizer.java:115)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2018-04-20 10:04:31,611-[TS] INFO pool-3-thread-1 com.tpt.nm.biz.mos.service.impl.ManagedObjectSynchronizer - Start to sync port info!
2018-04-20 10:04:32,819-[TS] INFO pool-9-thread-6356 com.tpt.nm.biz.alert.service.impl.AlertManager$$EnhancerByGuice$$c3841020 - Quering alerts with url `alert_cookies?limit=10000000&offset=0&order=id+asc&@confirm_user=[is]null&@triggered_at=%5B%3E%5D2018-04-20T09%3A45%3A15.451%2B08%3A00`
2018-04-20 10:04:38,118-[TS] INFO pool-9-thread-6379 com.tpt.nm.biz.rest.resources.managed_object.NetworkDeviceExecutionResource - Received parameters with task=`reload` and devices=`2825`
2018-04-20 10:04:38,119-[TS] INFO pool-9-thread-6379 com.tpt.nm.biz.mos.service.impl.ManagedObjectSynchronizer - Dispatch synchronize request for device `192.168.1.126`
2018-04-20 10:04:38,145-[TS] INFO pool-3-thread-2 com.tpt.nm.biz.mos.service.impl.ManagedObjectSynchronizer - Begin to synchronize device `192.168.1.126`
2018-04-20 10:04:38,146-[TS] INFO pool-3-thread-2 com.tpt.nm.biz.mos.service.impl.ManagedObjectSynchronizer - Start to sync sys info!
2018-04-20 10:04:38,167-[TS] ERROR pool-3-thread-2 com.tpt.nm.biz.mos.service.impl.ManagedObjectSynchronizer - Failed to sync sys!
{"errorCode": 400102, "errorMessage": "snmp is missing."}
	at com.tpt.nm.metrics.SamplingError.toException(SamplingError.java:50)
	at com.tpt.nm.metrics.ExchangeResponse.toObject(ExchangeResponse.java:113)
	at com.tpt.nm.metrics.ExchangeResult.toObject(ExchangeResult.java:248)
	at com.tpt.nm.biz.mos.service.impl.MetricBrowseManager.getMetricOfMo(MetricBrowseManager.java:63)
	at com.tpt.nm.biz.mos.service.impl.ManagedObjectSynchronizer.setSysForHost(ManagedObjectSynchronizer.java:593)
	at com.tpt.nm.biz.mos.service.impl.ManagedObjectSynchronizer.syncSysInfo(ManagedObjectSynchronizer.java:424)
	at com.tpt.nm.biz.mos.service.impl.ManagedObjectSynchronizer.syncDevice(ManagedObjectSynchronizer.java:252)
	at com.tpt.nm.biz.mos.service.impl.ManagedObjectSynchronizer.access$000(ManagedObjectSynchronizer.java:40)
	at com.tpt.nm.biz.mos.service.impl.ManagedObjectSynchronizer$2.run(ManagedObjectSynchronizer.java:115)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2018-04-20 10:04:38,168-[TS] INFO pool-3-thread-2 com.tpt.nm.biz.mos.service.impl.ManagedObjectSynchronizer - Start to sync port info!
2018-04-20 10:04:42,373-[TS] INFO pool-9-thread-6395 com.tpt.nm.biz.rest.resources.alert.AlertEventsResource - Getting alerts with include_confirmed = 'false'!
2018-04-20 10:04:43,673-[TS] INFO pool-9-thread-6407 com.tpt.nm.biz.alert.service.impl.AlertManager$$EnhancerByGuice$$c3841020 - Quering alerts with url `alert_cookies?limit=10000000&offset=0&order=id+asc&@confirm_user=[is]null&@triggered_at=%5B%3E%5D2018-04-20T09%3A45%3A15.461%2B08%3A00`
2018-04-20 10:04:49,014-[TS] WARN RedisQueuemetrics_arrive com.tpt.nm.biz.mos.service.impl.NetworkStatusMonitor - Found no field `swap_used_per` from value `{"vm_used_per":72,"total":17098637312,"vm_used":12378271744,"used_per":69,"vm_total":17098637312,"used":11804946432,"free":5293690880,"vm_free":4720365568}`
2018-04-20 10:04:53,752-[TS] INFO pool-9-thread-6334 com.tpt.nm.biz.alert.service.impl.AlertManager$$EnhancerByGuice$$c3841020 - Quering alerts with url `alert_cookies?limit=10000000&offset=0&order=id+asc&@confirm_user=[is]null&@triggered_at=%5B%3E%5D2018-04-20T09%3A45%3A15.471%2B08%3A00`
2018-04-20 10:04:58,472-[TS] WARN RedisQueuemetrics_arrive com.tpt.nm.biz.mos.service.impl.NetworkStatusMonitor - Found no field `swap_used_per` from value `{"vm_used_per":62,"total":4293488640,"vm_used":5506441216,"used_per":72,"vm_total":8833966080,"used":3131912192,"free":1161576448,"vm_free":3327524864}`
2018-04-20 10:05:03,772-[TS] INFO pool-9-thread-6374 com.tpt.nm.biz.alert.service.impl.AlertManager$$EnhancerByGuice$$c3841020 - Quering alerts with url `alert_cookies?limit=10000000&offset=0&order=id+asc&@confirm_user=[is]null&@triggered_at=%5B%3E%5D2018-04-20T09%3A45%3A15.481%2B08%3A00`
2018-04-20 10:05:14,434-[TS] INFO pool-9-thread-6453 com.tpt.nm.biz.alert.service.impl.AlertManager$$EnhancerByGuice$$c3841020 - Quering alerts with url `alert_cookies?limit=10000000&offset=0&order=id+asc&@confirm_user=[is]null&@triggered_at=%5B%3E%5D2018-04-20T09%3A45%3A15.491%2B08%3A00`
2018-04-20 10:05:25,419-[TS] INFO pool-9-thread-6475 com.tpt.nm.biz.alert.service.impl.AlertManager$$EnhancerByGuice$$c3841020 - Quering alerts with url `alert_cookies?limit=10000000&offset=0&order=id+asc&@confirm_user=[is]null&@triggered_at=%5B%3E%5D2018-04-20T09%3A45%3A15.501%2B08%3A00`

**Comment by eeiceyes** [comment]
fixed
