### ISSUE TITLE
实时流量看不到

### ISSUE THREAD

**Issue by runner-mei** [three-plus-three/hw_issues#212]
```
2016-03-30 05:52:49,862-[TS] ERROR pool-7-thread-1 com.tpt.nm.biz.rest.resources.managed_object.NetworkDevicePortFluxResource - Failed to get flux
com.alibaba.fastjson.JSONException: Illegal embedded sign character
    at com.tpt.nm.share.utils.TypeUtils.castToJavaBean(TypeUtils.java:796)
    at com.tpt.nm.share.utils.TypeUtils.cast(TypeUtils.java:489)
    at com.tpt.nm.metrics.ExchangeResponse.toObject(ExchangeResponse.java:117)
    at com.tpt.nm.metrics.ExchangeResult.toObject(ExchangeResult.java:188)
    at com.tpt.nm.biz.rest.resources.managed_object.NetworkDevicePortFluxResource.getFlux(NetworkDevicePortFluxResource.java:87)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:137)
    at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:280)
    at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:234)
    at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:221)
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:356)
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:179)
    at org.jboss.resteasy.plugins.server.netty.RequestDispatcher.service(RequestDispatcher.java:81)
    at org.jboss.resteasy.plugins.server.netty.RequestHandler.messageReceived(RequestHandler.java:56)
    at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
    at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
    at org.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:43)
    at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:67)
    at org.jboss.netty.handler.execution.OrderedMemoryAwareThreadPoolExecutor$ChildExecutor.run(OrderedMemoryAwareThreadPoolExecutor.java:314)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NumberFormatException: Illegal embedded sign character
    at java.math.BigInteger.<init>(BigInteger.java:312)
    at java.math.BigInteger.<init>(BigInteger.java:476)
    at com.tpt.nm.share.utils.TypeUtils.castToBigInteger(TypeUtils.java:166)
    at com.tpt.nm.share.utils.TypeUtils.cast(TypeUtils.java:553)
    at com.tpt.nm.share.utils.TypeUtils.cast(TypeUtils.java:636)
    at com.tpt.nm.share.utils.TypeUtils.castToJavaBean(TypeUtils.java:782)
    ... 25 more
2016-03-30 05:52:58,743-[TS] ERROR pool-7-thread-1 com.tpt.nm.biz.rest.resources.managed_object.NetworkDevicePortFluxResource - Failed to get flux
com.alibaba.fastjson.JSONException: Illegal embedded sign character
    at com.tpt.nm.share.utils.TypeUtils.castToJavaBean(TypeUtils.java:796)
    at com.tpt.nm.share.utils.TypeUtils.cast(TypeUtils.java:489)
    at com.tpt.nm.metrics.ExchangeResponse.toObject(ExchangeResponse.java:117)
    at com.tpt.nm.metrics.ExchangeResult.toObject(ExchangeResult.java:188)
    at com.tpt.nm.biz.rest.resources.managed_object.NetworkDevicePortFluxResource.getFlux(NetworkDevicePortFluxResource.java:87)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:137)
    at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:280)
    at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:234)
    at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:221)
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:356)
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:179)
    at org.jboss.resteasy.plugins.server.netty.RequestDispatcher.service(RequestDispatcher.java:81)
    at org.jboss.resteasy.plugins.server.netty.RequestHandler.messageReceived(RequestHandler.java:56)
    at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
    at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
    at org.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:43)
    at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:67)
    at org.jboss.netty.handler.execution.OrderedMemoryAwareThreadPoolExecutor$ChildExecutor.run(OrderedMemoryAwareThreadPoolExecutor.java:314)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NumberFormatException: Illegal embedded sign character
    at java.math.BigInteger.<init>(BigInteger.java:312)
    at java.math.BigInteger.<init>(BigInteger.java:476)
    at com.tpt.nm.share.utils.TypeUtils.castToBigInteger(TypeUtils.java:166)
    at com.tpt.nm.share.utils.TypeUtils.cast(TypeUtils.java:553)
    at com.tpt.nm.share.utils.TypeUtils.cast(TypeUtils.java:636)
    at com.tpt.nm.share.utils.TypeUtils.castToJavaBean(TypeUtils.java:782)
    ... 25 more
```

**Comment by eeiceyes** [comment]
目前无法重现

**Comment by runner-mei** [comment]
fix?
