### ISSUE TITLE
[华东电网] swaps 指标在创建巡检规则中查看所有数据出错，但在创建告警规则中是可以的

### ISSUE THREAD

**Issue by runner-mei** [three-plus-three/hw_issues#309]
````

[error] play - Cannot invoke the action, eventually got an error: java.util.NoSuchElementException: No value present
[error] application - 

! @701ccakc7 - Internal server error, for (GET) [/hengwei/system_settings/mo_kpi_params?mo_type=service_host&sub_type=hp_unix&seg_type=&mo_id=6439&metric=swaps&random_ts=1462246646915&screen_width=1920&screen_height=1049] ->

play.api.Application$$anon$1: Execution exception[[NoSuchElementException: No value present]]
	at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.11.1.jar:na]
Caused by: java.util.NoSuchElementException: No value present
	at com.tpt.nm.Optional.get(Optional.java:113) ~[extreme.extreme-share-2.2.jar:na]
	at controllers.SystemController$$anonfun$getMoKpiParams$1.apply(SystemController.scala:610) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at controllers.SystemController$$anonfun$getMoKpiParams$1.apply(SystemController.scala:598) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:433) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:432) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
[error] application - Server exception happened
play.api.Application$$anon$1: Execution exception[[NoSuchElementException: No value present]]
	at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.11.1.jar:na]
Caused by: java.util.NoSuchElementException: No value present
	at com.tpt.nm.Optional.get(Optional.java:113) ~[extreme.extreme-share-2.2.jar:na]
	at controllers.SystemController$$anonfun$getMoKpiParams$1.apply(SystemController.scala:610) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at controllers.SystemController$$anonfun$getMoKpiParams$1.apply(SystemController.scala:598) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:433) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:432) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
[error] application - Get `HTTP/1.1 404 Not Found` from rest server, errors => ``
[error] play - Cannot invoke the action, eventually got an error: java.lang.RuntimeException: 
````

**Comment by eeiceyes** [comment]
fixed
