### ISSUE TITLE
[华东电网] 取 cpu 失败，什么主机不知道，只看到下面的错误

### ISSUE THREAD

**Issue by runner-mei** [three-plus-three/hw_issues#310]
````
[error] application - Failed to parse json `{"raw":{"total":2155871124,"stealstolen":0,"other":0,"irq":0,"nice":0,"timestamp":"0001-01-01T00:00:00Z","idle":2150643722,"system":4057371,"softirq":0,"name":"","guest":0,"iowait":0,"slot":0,"user":1170031},"cpu_percent":1.806478405315616,"system_percent":1.7148719953097518,"idle_percent":98.19352159468438,"cpu":1.806478405315616,"user_percent":0.09160641000586281}`
com.alibaba.fastjson.JSONException: syntax error, expect [, actual {, pos 0
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:1014) ~[com.alibaba.fastjson-1.2.4.jar:na]
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:1001) ~[com.alibaba.fastjson-1.2.4.jar:na]
	at com.alibaba.fastjson.JSON.parseArray(JSON.java:323) ~[com.alibaba.fastjson-1.2.4.jar:na]
	at helpers.ServiceHelper$.resolveLinuxCpu(ServiceHelper.scala:465) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at controllers.HostIntegrationController$$anonfun$getLinuxCpu$1.apply(HostIntegrationController.scala:40) [tpt_web.tpt_web-2.2.jar:2.2]
````

**Comment by eeiceyes** [comment]
指标名cpuinfo，snmp方式取回来是个数组

{"channel":"","request_id":0,"created_at":"2016-05-03T17:30:27.9002906+08:00","value":[{"all":557825107,"cpu_percent":96.64942610767069,"guest":0,"idle":448179340,"idle_percent":99,"iowait":7732,"irq":108889971,"nice":15236,"other":0,"softirq":2067,"stealstolen":0,"system":216580,"system_percent":0,"user":514181,"user_percent":0}],"method_id":"oscpu_ucd","engine_id":0}

**Comment by runner-mei** [comment]
它是一个数组啊，元模型中它也是一个数组啊

**Comment by runner-mei** [comment]
已修复
