### ISSUE TITLE
[华东电网]  hp-linux 运转图中的端口流量没有

### ISSUE THREAD

**Issue by runner-mei** [three-plus-three/hw_issues#312]
```

! @701cg01f2 - Internal server error, for (GET) [/hengwei/service_hosts/3067/integrations/linux_network_flux?hideTip=true&random_ts=1462248286352&screen_width=1920&screen_height=1049] ->

play.api.Application$$anon$1: Execution exception[[RuntimeException: ]]
    at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.11.1.jar:na]
Caused by: java.lang.RuntimeException: 
    at lib.rest.Base$class.sendRequest(Base.scala:129) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Base$class.getObjectArray(Base.scala:43) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Devices$.getObjectArray(Devices.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Devices$.getPortFlux(Devices.scala:63) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at helpers.ServiceHelper$.resolveLinuxNetworkFlux(ServiceHelper.scala:430) ~[tpt_web.tpt_web-2.2.jar:2.2]
[error] application - Server exception happened
play.api.Application$$anon$1: Execution exception[[RuntimeException: ]]
    at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.11.1.jar:na]
Caused by: java.lang.RuntimeException: 
    at lib.rest.Base$class.sendRequest(Base.scala:129) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Base$class.getObjectArray(Base.scala:43) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Devices$.getObjectArray(Devices.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Devices$.getPortFlux(Devices.scala:63) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at helpers.ServiceHelper$.resolveLinuxNetworkFlux(ServiceHelper.scala:430) ~[tpt_web.tpt_web-2.2.jar:2.2]
```

**Comment by eeiceyes** [comment]
指标名cpuinfo，snmp方式取回来是个数组

{"channel":"","request_id":0,"created_at":"2016-05-03T17:30:27.9002906+08:00","value":[{"all":557825107,"cpu_percent":96.64942610767069,"guest":0,"idle":448179340,"idle_percent":99,"iowait":7732,"irq":108889971,"nice":15236,"other":0,"softirq":2067,"stealstolen":0,"system":216580,"system_percent":0,"user":514181,"user_percent":0}],"method_id":"oscpu_ucd","engine_id":0}

**Comment by eeiceyes** [comment]
刷新下设备，然后再看属性页面中的端口列表是否为空，如为空，则确实娶不到数

**Comment by eeiceyes** [comment]
在倒回来的数据库中看到该设备的端口列表确实为空，在现场通过url取下数据，指标名为interface_descr，设备id为3067

**Comment by runner-mei** [comment]
错误描述能改进一下么？

**Comment by Cuic** [comment]
待去客户现场验证

**Comment by Cuic** [comment]
Hp-linux运作图中没有端口流量
url获取interface的结果：
····
{"channel":"","request_id":0,"created_at":"2016-05-18T11:40:10.3568546+08:00","value":[{"ifAdminStatus":1,"ifAdminStatus__descr":"up","ifBit":32,"ifDescr":"lan0 HP PCI-X 1000Base-T Release B.11.23.0505.02","ifInDiscards":0,"ifInErrors":0,"ifInNUcastPkts":0,"ifInOctets":0,"ifInUcastPkts":0,"ifInUnknownProtos":0,"ifIndex":1,"ifLastChange":0,"ifMtu":1500,"ifOpStatus":2,"ifOpStatus__descr":"down","ifOutDiscards":0,"ifOutErrors":0,"ifOutNUcastPkts":0,"ifOutOctets":0,"ifOutQLen":0,"ifOutUcastPkts":0,"ifPhysAddress":"00:15:60:04:a9:58","ifSpecific":"1.3.6.1.2.1.10.7","ifSpeed":100000000,"ifStatus":0,"ifStatus__descr":"DOWN","ifType":6,"ifType__descr":"ethernetCsmacd(6)"},{"ifAdminStatus":1,"ifAdminStatus__descr":"up","ifBit":32,"ifDescr":"lan1 HP PCI-X 1000Base-T Release B.11.23.0505.02","ifInDiscards":0,"ifInErrors":0,"ifInNUcastPkts":147632813,"ifInOctets":1869575636,"ifInUcastPkts":83754466,"ifInUnknownProtos":161,"ifIndex":2,"ifLastChange":217,"ifMtu":1500,"ifOpStatus":1,"ifOpStatus__descr":"up","ifOutDiscards":0,"ifOutErrors":0,"ifOutNUcastPkts":18819,"ifOutOctets":1307968533,"ifOutQLen":1,"ifOutUcastPkts":80125667,"ifPhysAddress":"00:15:60:04:a9:59","ifSpecific":"1.3.6.1.2.1.10.7","ifSpeed":1000000000,"ifStatus":1,"ifStatus__descr":"UP","ifType":6,"ifType__descr":"ethernetCsmacd(6)"},{"ifAdminStatus":1,"ifAdminStatus__descr":"up","ifBit":32,"ifDescr":"software loopback","ifInDiscards":0,"ifInErrors":0,"ifInNUcastPkts":0,"ifInOctets":407141420,"ifInUcastPkts":7072918,"ifInUnknownProtos":0,"ifIndex":3,"ifLastChange":0,"ifMtu":4136,"ifOpStatus":1,"ifOpStatus__descr":"up","ifOutDiscards":0,"ifOutErrors":0,"ifOutNUcastPkts":0,"ifOutOctets":407141420,"ifOutQLen":0,"ifOutUcastPkts":7072918,"ifPhysAddress":"","ifSpecific":"1.3.6.1.2.1.10.7","ifSpeed":100000000,"ifStatus":1,"ifStatus__descr":"UP","ifType":24,"ifType__descr":"softwareLoopback(24)"}],"method_id":"interface_default","engine_id":0,"enumeration_context":"3"}
····
log:
····
[error] application - Get `HTTP/1.1 404 Not Found` from rest server, errors => ``
[error] play - Cannot invoke the action, eventually got an error: java.lang.RuntimeException: 
[error] application - 

! @7054k4d41 - Internal server error, for (GET) [/hengwei/service_hosts/3067/integrations/linux_network_flux?hideTip=true&random_ts=1451899605672&screen_width=1920&screen_height=1049] ->

play.api.Application$$anon$1: Execution exception[[RuntimeException: ]]
	at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.11.1.jar:na]
Caused by: java.lang.RuntimeException: 
	at lib.rest.Base$class.sendRequest(Base.scala:129) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Base$class.getObjectArray(Base.scala:43) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Devices$.getObjectArray(Devices.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Devices$.getPortFlux(Devices.scala:63) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at helpers.ServiceHelper$.resolveLinuxNetworkFlux(ServiceHelper.scala:442) ~[tpt_web.tpt_web-2.2.jar:2.2]
[error] application - Server exception happened
play.api.Application$$anon$1: Execution exception[[RuntimeException: ]]
	at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.11.1.jar:na]
Caused by: java.lang.RuntimeException: 
	at lib.rest.Base$class.sendRequest(Base.scala:129) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Base$class.getObjectArray(Base.scala:43) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Devices$.getObjectArray(Devices.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Devices$.getPortFlux(Devices.scala:63) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at helpers.ServiceHelper$.resolveLinuxNetworkFlux(ServiceHelper.scala:442) ~[tpt_web.tpt_web-2.2.jar:2.2]
[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `发生多个错误`
[error] application - Failed to get value of metric[loadavg] for mo[service_host][3067]
java.lang.RuntimeException: 发生多个错误
	at lib.rest.Base$class.sendRequest(Base.scala:129) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Base$class.getJSON(Base.scala:28) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at helpers.ServiceHelper$.getValueJson(ServiceHelper.scala:1788) [tpt_web.tpt_web-2.2.jar:2.2]
[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `发生多个错误`
[error] application - Failed to get value of metric[vmstat_rate] for mo[service_host][3067]
java.lang.RuntimeException: 发生多个错误
	at lib.rest.Base$class.sendRequest(Base.scala:129) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Base$class.getJSON(Base.scala:28) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at helpers.ServiceHelper$.getValueJson(ServiceHelper.scala:1788) [tpt_web.tpt_web-2.2.jar:2.2]
[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `发生多个错误`
[error] application - Failed to get value of metric[vmstat_rate] for mo[service_host][3067]
java.lang.RuntimeException: 发生多个错误
	at lib.rest.Base$class.sendRequest(Base.scala:129) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Base$class.getJSON(Base.scala:28) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at helpers.ServiceHelper$.getValueJson(ServiceHelper.scala:1788) [tpt_web.tpt_web-2.2.jar:2.2]
[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `发生多个错误`
[error] application - Failed to get value of metric[iostat_rate] for mo[service_host][3067]
java.lang.RuntimeException: 发生多个错误
	at lib.rest.Base$class.sendRequest(Base.scala:129) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Base$class.getJSON(Base.scala:28) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at helpers.ServiceHelper$.getValueJson(ServiceHelper.scala:1788) [tpt_web.tpt_web-2.2.jar:2.2]
[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `'NetScaler NS9.3: Build 56.5.nc, Date: May  1 2012, 09:53:56  ' is syntex error.`
[error] application - Failed to get value of metric[base_information] for mo[service_host][6691]
java.lang.RuntimeException: 'NetScaler NS9.3: Build 56.5.nc, Date: May  1 2012, 09:53:56  ' is syntex error.
	at lib.rest.Base$class.sendRequest(Base.scala:129) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Base$class.getJSON(Base.scala:28) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at helpers.ServiceHelper$.getValueObject(ServiceHelper.scala:1800) [tpt_web.tpt_web-2.2.jar:2.2]
[warn] application - Failed to get '.os' as string from {}
[warn] application - Failed to get '.issue' as string from {}
[warn] application - Failed to get '.name' as string from {}
[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `不支持这个指标`
[error] application - Failed to get value of metric[login_user.count()] for mo[service_host][6691]
java.lang.RuntimeException: 不支持这个指标
	at lib.rest.Base$class.sendRequest(Base.scala:129) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Base$class.getJSON(Base.scala:28) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at helpers.ServiceHelper$.getValue(ServiceHelper.scala:1836) [tpt_web.tpt_web-2.2.jar:2.2]
[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `采集结果为空`
[error] application - Failed to get value of metric[tcp_connection] for mo[service_host][6691]
java.lang.RuntimeException: 采集结果为空
	at lib.rest.Base$class.sendRequest(Base.scala:129) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Base$class.getJSON(Base.scala:28) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
····
