### ISSUE TITLE
节点数超出License限制, 添加中间件失败, 出错信息不正确

### ISSUE THREAD

**Issue by runner-mei** [three-plus-three/hw_issues#317]
![_2016-05-04t10-14-22 974z](https://cloud.githubusercontent.com/assets/1052632/15011380/127075a8-1224-11e6-9b3b-9bbe956ed4ae.png)

web_server.log 中日志如下
````
[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `java.lang.RuntimeException: {"errorCode": 910400, "errorMessage": "节点数超出License限制！"}`
[error] play - Cannot invoke the action, eventually got an error: java.lang.RuntimeException: 未知错误导致操作失败！
[error] application - 

! @701lj19f0 - Internal server error, for (POST) [/hengwei/service_midwares] ->

play.api.Application$$anon$1: Execution exception[[RuntimeException: 未知错误导致操作失败！]]
	at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.11.1.jar:na]
Caused by: java.lang.RuntimeException: 未知错误导致操作失败！
	at lib.rest.Base$class.sendRequest(Base.scala:127) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Base$class.postJson(Base.scala:59) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Midwares$.postJson(Midwares.scala:9) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Midwares$.create(Midwares.scala:11) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at controllers.MidwareController$$anonfun$create$1$$anonfun$apply$4.apply(MidwareController.scala:64) ~[tpt_web.tpt_web-2.2.jar:2.2]
````

server_biz.log 中日志如下
````
ERROR pool-7-thread-133 com.tpt.nm.share.exception.RestApplicationExceptionMapper - ApplicationException was thrown!
org.jboss.resteasy.spi.ApplicationException: java.lang.RuntimeException: {"errorCode": 910400, "errorMessage": "节点数超出License限制！"}
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:146)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:280)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:234)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:221)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:356)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:179)
	at org.jboss.resteasy.plugins.server.netty.RequestDispatcher.service(RequestDispatcher.java:81)
	at org.jboss.resteasy.plugins.server.netty.RequestHandler.messageReceived(RequestHandler.java:56)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:43)
	at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:67)
	at org.jboss.netty.handler.execution.OrderedMemoryAwareThreadPoolExecutor$ChildExecutor.run(OrderedMemoryAwareThreadPoolExecutor.java:314)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: {"errorCode": 910400, "errorMessage": "节点数超出License限制！"}
	at com.tpt.nm.share.eventbus.EventBus.post(EventBus.java:270)
	at com.tpt.nm.biz.mos.service.impl.ServiceManagedObjectManager.createMidware(ServiceManagedObjectManager.java:149)
	at com.tpt.nm.biz.rest.resources.managed_object.ServiceMidwaresResource.createMidware(ServiceMidwaresResource.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:137)
	... 16 more
Caused by: {"errorCode": 910400, "errorMessage": "节点数超出License限制！"}
	at com.tpt.nm.biz.Errors.throwException(Errors.java:91)
	at com.tpt.nm.biz.system.service.impl.LicenseManager.listen(LicenseManager.java:63)
````

**Comment by eeiceyes** [comment]
fixed

**Comment by eeiceyes** [comment]
顾来验证下吧，我刚签入
