### ISSUE TITLE
添加数据库告警规则，更多指标出错

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#318]
描述：
添加oracle数据库指标告警'点击“更多指标”报错如下图：

![image](https://cloud.githubusercontent.com/assets/14171497/15011434/6052f78c-1224-11e6-848b-d37e5fa258e2.png)

web_server.log如下：
````
[error] application - 

! @701ljdgif - Internal server error, for (GET) [/hengwei/alert_kpis/kpis_more?managed_type=service_database&category=oracle&selected=&random_ts=1462356827177&screen_width=1366&screen_height=738] ->

play.api.Application$$anon$1: Execution exception[[IllegalArgumentException: Multiple entries with same key: value=com.tpt.nm.meta.PropertySpec@138b370 and value=com.tpt.nm.meta.PropertySpec@18c7eb0]]
	at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.11.1.jar:na]
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: value=com.tpt.nm.meta.PropertySpec@138b370 and value=com.tpt.nm.meta.PropertySpec@18c7eb0
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:136) ~[com.google.guava.guava-19.0.jar:na]
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:98) ~[com.google.guava.guava-19.0.jar:na]
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:84) ~[com.google.guava.guava-19.0.jar:na]
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:295) ~[com.google.guava.guava-19.0.jar:na]
	at com.tpt.nm.meta.ClassSpec.properties(ClassSpec.java:266) ~[extreme.extreme-model-2.2.jar:na]
[error] application - Server exception happened
play.api.Application$$anon$1: Execution exception[[IllegalArgumentException: Multiple entries with same key: value=com.tpt.nm.meta.PropertySpec@138b370 and value=com.tpt.nm.meta.PropertySpec@18c7eb0]]
	at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.11.1.jar:na]
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: value=com.tpt.nm.meta.PropertySpec@138b370 and value=com.tpt.nm.meta.PropertySpec@18c7eb0
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:136) ~[com.google.guava.guava-19.0.jar:na]
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:98) ~[com.google.guava.guava-19.0.jar:na]
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:84) ~[com.google.guava.guava-19.0.jar:na]
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:295) ~[com.google.guava.guava-19.0.jar:na]
	at com.tpt.nm.meta.ClassSpec.properties(ClassSpec.java:266) ~[extreme.extreme-model-2.2.jar:na]
````

**Comment by eeiceyes** [comment]
父类和子类的指标重复了

**Comment by runner-mei** [comment]
fixed
