### ISSUE TITLE
[华东电网] 账号自己修改密码后丢失所有权限

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#341]
描述：创建的账号，登陆后修改密码后，赋予的权限丢失(赋予的角色为空)。

````
[error] play - Cannot invoke the action, eventually got an error: java.lang.RuntimeException: org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.postgresql.util.PSQLException: ERROR: syntax error at or near ")"
  位置：78
### The error may exist in com/tpt/nm/biz/mos/dao/NetworkMapper.xml
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: select count(*) from tpt_network_link_view where 1=1 and (from_device_id in () and to_device_id in ())
### Cause: org.postgresql.util.PSQLException: ERROR: syntax error at or near ")"
  位置：78
[error] application - 

! @705i27dad - Internal server error, for (GET) [/hengwei/layouts/shortcut?hideTip&random_ts=1452057824379&screen_width=1920&screen_height=1049] ->

play.api.Application$$anon$1: Execution exception[[RuntimeException: org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.postgresql.util.PSQLException: ERROR: syntax error at or near ")"
  位置：78
### The error may exist in com/tpt/nm/biz/mos/dao/NetworkMapper.xml
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: select count(*) from tpt_network_link_view where 1=1 and (from_device_id in () and to_device_id in ())
### Cause: org.postgresql.util.PSQLException: ERROR: syntax error at or near ")"
  位置：78]]
	at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.11.1.jar:na]
Caused by: java.lang.RuntimeException: org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.postgresql.util.PSQLException: ERROR: syntax error at or near ")"
  位置：78
### The error may exist in com/tpt/nm/biz/mos/dao/NetworkMapper.xml
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: select count(*) from tpt_network_link_view where 1=1 and (from_device_id in () and to_device_id in ())
### Cause: org.postgresql.util.PSQLException: ERROR: syntax error at or near ")"
  位置：78
	at lib.rest.Base$class.sendRequest(Base.scala:129) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Base$class.getObject(Base.scala:48) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Links$.getObject(Links.scala:9) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Links$.count(Links.scala:37) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at views.html.layouts.topbar_stat$.apply(topbar_stat.template.scala:35) ~[tpt_web.tpt_web-2.2.jar:2.2]
[error] application - Server exception happened
play.api.Application$$anon$1: Execution exception[[RuntimeException: org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.postgresql.util.PSQLException: ERROR: syntax error at or near ")"
  位置：78
### The error may exist in com/tpt/nm/biz/mos/dao/NetworkMapper.xml
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: select count(*) from tpt_network_link_view where 1=1 and (from_device_id in () and to_device_id in ())
### Cause: org.postgresql.util.PSQLException: ERROR: syntax error at or near ")"
  位置：78]]
	at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.11.1.jar:na]
Caused by: java.lang.RuntimeException: org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.postgresql.util.PSQLException: ERROR: syntax error at or near ")"
  位置：78
### The error may exist in com/tpt/nm/biz/mos/dao/NetworkMapper.xml
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: select count(*) from tpt_network_link_view where 1=1 and (from_device_id in () and to_device_id in ())
### Cause: org.postgresql.util.PSQLException: ERROR: syntax error at or near ")"
  位置：78
	at lib.rest.Base$class.sendRequest(Base.scala:129) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Base$class.getObject(Base.scala:48) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Links$.getObject(Links.scala:9) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Links$.count(Links.scala:37) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at views.html.layouts.topbar_stat$.apply(topbar_stat.template.scala:35) ~[tpt_web.tpt_web-2.2.jar:2.2]

````

**Comment by eeiceyes** [comment]
fixed
