### ISSUE TITLE
[华东电网] SUSE-linux 运作试图没有端口流量

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#342]
SUSE-linux 运作图中没有端口流量
URL获取interace结果：设备ID：6463
{"channel":"","request_id":0,"created_at":"2016-05-18T13:03:38.1795418+08:00","value":[{"if78":"AC:C0:FA:47:EC","ifAdminStatus":1,"ifAdminStatus__descr":"up","ifBit":64,"ifDescr":"Could","ifInDiscards":"0","ifInErrors":"0","ifInFrames":"0","ifInOctets":172312858,"ifInOverruns":"0","ifInUcastPkts":"1432041","ifIndex":760615380,"ifMetric":"1","ifMtu":"1500","ifName":"Could","ifNet6addr":"fe80::7aac:c0ff:fefa:47ec/64","ifNet6scope":"Link","ifOpStatus":1,"ifOpStatus__descr":"up","ifOutCarrier":"0","ifOutCollisions":"0","ifOutDiscards":"0","ifOutErrors":"0","ifOutOctets":153633444,"ifOutOverruns":"0","ifOutTxqueuelen":"1000","ifOutUcastPkts":"1371829","ifOutinterrupt":"16","ifOutmemory":"f4000000-f4012700","ifPhysAddress":"","ifStatus":1,"ifStatus__descr":"UP","ifType":6,"ifType__descr":"ethernetCsmacd(6)","ifencap":"Ethernet"},{"ifAdminStatus":1,"ifAdminStatus__descr":"up","ifBit":64,"ifDescr":"eth1","ifInDiscards":"0","ifInErrors":"0","ifInFrames":"0","ifInOctets":178700773,"ifInOverruns":"0","ifInUcastPkts":"1504196","ifIndex":10001,"ifMetric":"1","ifMtu":"1500","ifName":"eth1","ifNet6addr":"fe80::7aac:c0ff:fefa:47ee/64","ifNet6scope":"Link","ifOpStatus":1,"ifOpStatus__descr":"up","ifOutCarrier":"0","ifOutCollisions":"0","ifOutDiscards":"0","ifOutErrors":"0","ifOutOctets":153422371,"ifOutOverruns":"0","ifOutTxqueuelen":"1000","ifOutUcastPkts":"1371623","ifOutinterrupt":"17","ifOutmemory":"f2000000-f2012700","ifPhysAddress":"","ifStatus":1,"ifStatus__descr":"UP","ifType":6,"ifType__descr":"ethernetCsmacd(6)"},{"ifAdminStatus":1,"ifAdminStatus__descr":"up","ifBit":64,"ifDescr":"eth2","ifInDiscards":"0","ifInErrors":"0","ifInFrames":"0","ifInOctets":200945728,"ifInOverruns":"0","ifInUcastPkts":"2154460","ifIndex":10002,"ifMetric":"1","ifMtu":"1500","ifName":"eth2","ifNet6addr":"fe80::7aac:c0ff:fefa:47f0/64","ifNet6scope":"Link","ifNetaddr":"10.128.7.73","ifNetbcast":"10.128.7.255","ifNetmask":"255.255.255.0","ifOpStatus":1,"ifOpStatus__descr":"up","ifOutCarrier":"0","ifOutCollisions":"0","ifOutDiscards":"0","ifOutErrors":"0","ifOutOctets":224393988,"ifOutOverruns":"0","ifOutTxqueuelen":"1000","ifOutUcastPkts":"1259067","ifOutinterrupt":"18","ifOutmemory":"f8000000-f8012700","ifPhysAddress":"","ifStatus":1,"ifStatus__descr":"UP","ifType":6,"ifType__descr":"ethernetCsmacd(6)"},{"ifAdminStatus":1,"ifAdminStatus__descr":"up","ifBit":64,"ifDescr":"lo","ifInDiscards":"0","ifInErrors":"0","ifInFrames":"0","ifInOctets":785477,"ifInOverruns":"0","ifInUcastPkts":"9112","ifIndex":2147483647,"ifMetric":"1","ifMtu":"16436","ifName":"lo","ifNet6addr":"::1/128","ifNet6scope":"Host","ifNetaddr":"127.0.0.1","ifNetmask":"255.0.0.0","ifOpStatus":1,"ifOpStatus__descr":"up","ifOutCarrier":"0","ifOutCollisions":"0","ifOutDiscards":"0","ifOutErrors":"0","ifOutOctets":785477,"ifOutOverruns":"0","ifOutTxqueuelen":"0","ifOutUcastPkts":"9112","ifPhysAddress":"","ifStatus":1,"ifStatus__descr":"UP","ifType":6,"ifType__descr":"ethernetCsmacd(6)"}],"method_id":"interfaces_by_ssh","engine_id":0}

log:

```
[error] application - Failed to get value of metric[login_user.count()] for mo[service_host][6463]
java.lang.RuntimeException: 发生多个错误
    at lib.rest.Base$class.sendRequest(Base.scala:129) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Base$class.getJSON(Base.scala:28) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at helpers.ServiceHelper$.getValue(ServiceHelper.scala:1836) [tpt_web.tpt_web-2.2.jar:2.2]
.getJSON(Base.scala:28) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at helpers.ServiceHelper$.getValueJson(ServiceHelper.scala:1788) [tpt_web.tpt_web-2.2.jar:2.2]
[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `发生多个错误`
[error] application - Failed to get value of metric[iostat_rate] for mo[service_host][3067]
java.lang.RuntimeException: 发生多个错误
    at lib.rest.Base$class.sendRequest(Base.scala:129) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Base$class.getJSON(Base.scala:28) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at helpers.ServiceHelper$.getValueJson(ServiceHelper.scala:1788) [tpt_web.tpt_web-2.2.jar:2.2]
[error] application - Get `HTTP/1.1 404 Not Found` from rest server, errors => ``
[error] play - Cannot invoke the action, eventually got an error: java.lang.RuntimeException: 
[error] application - 

! @705hmp0n4 - Internal server error, for (GET) [/hengwei/service_hosts/3067/integrations/linux_network_flux?hideTip=true&random_ts=1452055390183&screen_width=1920&screen_height=1048] ->

play.api.Application$$anon$1: Execution exception[[RuntimeException: ]]
    at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.11.1.jar:na]
Caused by: java.lang.RuntimeException: 
    at lib.rest.Base$class.sendRequest(Base.scala:129) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Base$class.getObjectArray(Base.scala:43) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Devices$.getObjectArray(Devices.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Devices$.getPortFlux(Devices.scala:63) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at helpers.ServiceHelper$.resolveLinuxNetworkFlux(ServiceHelper.scala:442) ~[tpt_web.tpt_web-2.2.jar:2.2]
[error] application - Server exception happened
play.api.Application$$anon$1: Execution exception[[RuntimeException: ]]
    at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.11.1.jar:na]
Caused by: java.lang.RuntimeException: 
    at lib.rest.Base$class.sendRequest(Base.scala:129) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Base$class.getObjectArray(Base.scala:43) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Devices$.getObjectArray(Devices.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Devices$.getPortFlux(Devices.scala:63) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at helpers.ServiceHelper$.resolveLinuxNetworkFlux(ServiceHelper.scala:442) ~[tpt_web.tpt_web-2.2.jar:2.2]
[error] application - Get 
```

**Comment by eeiceyes** [comment]
现场再去确认下，这个问题还存在吗？
