### ISSUE TITLE
[虚拟化bug] 虚拟化主机运行视图性能信息不显示

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#354]
虚拟化主机运行视图性能信息不显示
![image](https://cloud.githubusercontent.com/assets/14171497/15529920/88a1fb2e-2283-11e6-9c86-b203966216e6.png)

```
2016-05-25 14:13:53,583-[TS] ERROR pool-7-thread-2347 com.tpt.nm.biz.rest.resources.vmware_management.VMwareObjectsResource - Failed to get result
{"errorCode": 500, "errorMessage": "metric 'disk_provisioned_latest' isn't found."}
    at com.tpt.nm.metrics.SamplingError.toException(SamplingError.java:50)
    at com.tpt.nm.metrics.ExchangeResponse.toValueAsString(ExchangeResponse.java:154)
    at com.tpt.nm.metrics.ExchangeResult.toValueAsString(ExchangeResult.java:200)
    at com.tpt.nm.biz.rest.resources.vmware_management.VMwareObjectsResource.getStatuses(VMwareObjectsResource.java:61)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:137)
    at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:280)
    at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:234)
    at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:221)
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:356)
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:179)
    at org.jboss.resteasy.plugins.server.netty.RequestDispatcher.service(RequestDispatcher.java:81)
    at org.jboss.resteasy.plugins.server.netty.RequestHandler.messageReceived(RequestHandler.java:56)
    at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
    at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
    at org.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:43)
    at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:67)
    at org.jboss.netty.handler.execution.OrderedMemoryAwareThreadPoolExecutor$ChildExecutor.run(OrderedMemoryAwareThreadPoolExecutor.java:314)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
2016-05-25 14:13:53,894-[TS] ERROR pool-7-thread-2361 com.tpt.nm.biz.rest.resources.vmware_management.VMwareObjectsResource - Failed to get result
{"errorCode": 500, "errorMessage": "metric 'disk_provisioned_latest' isn't found."}
    at com.tpt.nm.metrics.SamplingError.toException(SamplingError.java:50)
    at com.tpt.nm.metrics.ExchangeResponse.toValueAsString(ExchangeResponse.java:154)
    at com.tpt.nm.metrics.ExchangeResult.toValueAsString(ExchangeResult.java:200)
    at com.tpt.nm.biz.rest.resources.vmware_management.VMwareObjectsResource.getStatuses(VMwareObjectsResource.java:61)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:137)
    at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:280)
    at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:234)
    at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:221)
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:356)
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:179)
    at org.jboss.resteasy.plugins.server.netty.RequestDispatcher.service(RequestDispatcher.java:81)
    at org.jboss.resteasy.plugins.server.netty.RequestHandler.messageReceived(RequestHandler.java:56)
    at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
    at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
    at org.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:43)
    at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:67)
    at org.jboss.netty.handler.execution.OrderedMemoryAwareThreadPoolExecutor$ChildExecutor.run(OrderedMemoryAwareThreadPoolExecutor.java:314)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

```

注意：重点解决

**Comment by eeiceyes** [comment]
2016-05-25 14:50:08,205-[TS] ERROR pool-7-thread-9 com.tpt.nm.biz.rest.resources.vmware_management.VMwareObjectsResource - Failed to get result
{"errorCode": 500, "errorMessage": "metric 'disk_usage_average' is unsupported."}
	at com.tpt.nm.metrics.SamplingError.toException(SamplingError.java:50)
	at com.tpt.nm.metrics.ExchangeResponse.toValueAsString(ExchangeResponse.java:154)
	at com.tpt.nm.metrics.ExchangeResult.toValueAsString(ExchangeResult.java:200)
2016-05-25 14:50:08,205-[TS] ERROR pool-7-thread-35 com.tpt.nm.biz.rest.resources.vmware_management.VMwareObjectsResource - Failed to get result
{"errorCode": 500, "errorMessage": "metric 'net_usage_average' is unsupported."}
	at com.tpt.nm.metrics.SamplingError.toException(SamplingError.java:50)
	at com.tpt.nm.metrics.ExchangeResponse.toValueAsString(ExchangeResponse.java:154)
	at com.tpt.nm.metrics.ExchangeResult.toValueAsString(ExchangeResult.java:200)
2016-05-25 14:50:08,203-[TS] ERROR pool-7-thread-35 com.tpt.nm.biz.rest.resources.vmware_management.VMwareObjectsResource - Failed to get result
{"errorCode": 500, "errorMessage": "metric 'disk_provisioned_latest' isn't found."}
	at com.tpt.nm.metrics.SamplingError.toException(SamplingError.java:50)
	at com.tpt.nm.metrics.ExchangeResponse.toValueAsString(ExchangeResponse.java:154)
	at com.tpt.nm.metrics.ExchangeResult.toValueAsString(ExchangeResult.java:200)
	at com.tpt.nm.biz.rest.resources.vmware_management.VMwareObjectsResource.getStatuses(VMwareObjectsResource.java:61)

**Comment by Cuic** [comment]
Linux IP地址取不到

**Comment by eeiceyes** [comment]
fixed

**Comment by hengwei-test** [comment]
hengwei_setup_2.3.20171027_450_x64.exe    版本确认，close处理。
hengwei_setup_3.2.20171027_2837_x64.exe   版本确认，close处理。
