### ISSUE TITLE
[华东电力] oracle数据库取不到指标

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#357]
oracle版本：10.2.0.4  （此版本取不到）  11.2.0.3（此版本可以取到）

使用URL获取数据返回：time out

```
[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `ORA-00942: table or view does not exist
`
[error] application - Failed to get value of metric[oracle_tablespace] for mo[service_database][6744]
java.lang.RuntimeException: ORA-00942: table or view does not exist

    at lib.rest.Base$class.sendRequest(Base.scala:131) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Base$class.getJSON(Base.scala:29) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at helpers.ServiceHelper$.getValueJson(ServiceHelper.scala:1802) [tpt_web.tpt_web-2.2.jar:2.2]
[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `'USE_DB_RECOVERY_FILE_DEST' is disabled.`
[error] application - Failed to get value of metric[oracle_archiver_stat] for mo[service_database][6644]
java.lang.RuntimeException: 'USE_DB_RECOVERY_FILE_DEST' is disabled.
    at lib.rest.Base$class.sendRequest(Base.scala:131) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Base$class.getJSON(Base.scala:29) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at helpers.ServiceHelper$.getValueJson(ServiceHelper.scala:1802) [tpt_web.tpt_web-2.2.jar:2.2]
[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `正在采集中`
[error] application - Failed to get value of metric[oracle_net_io_stat_rate] for mo[service_database][6644]
java.lang.RuntimeException: 正在采集中
    at lib.rest.Base$class.sendRequest(Base.scala:131) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Base$class.getJSON(Base.scala:29) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at helpers.ServiceHelper$.getValueJson(ServiceHelper.scala:1802) [tpt_web.tpt_web-2.2.jar:2.2]
[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `'USE_DB_RECOVERY_FILE_DEST' is disabled.`
[error] application - Failed to get value of metric[oracle_archiver_stat] for mo[service_database][6644]
java.lang.RuntimeException: 'USE_DB_RECOVERY_FILE_DEST' is disabled.
    at lib.rest.Base$class.sendRequest(Base.scala:131) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Base$class.getJSON(Base.scala:29) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at helpers.ServiceHelper$.getValueJson(ServiceHelper.scala:1802) [tpt_web.tpt_web-2.2.jar:2.2]
[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `请求超时`
[error] application - Failed to get value of metric[oracle_io_stat] for mo[service_database][6744]
java.lang.RuntimeException: 请求超时
    at lib.rest.Base$class.sendRequest(Base.scala:131) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Base$class.getJSON(Base.scala:29) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at helpers.ServiceHelper$.getValueJson(ServiceHelper.scala:1802) [tpt_web.tpt_web-2.2.jar:2.2]
[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `'USE_DB_RECOVERY_FILE_DEST' is disabled.`
[error] application - Failed to get value of metric[oracle_archiver_stat] for mo[service_database][6644]
java.lang.RuntimeException: 'USE_DB_RECOVERY_FILE_DEST' is disabled.
    at lib.rest.Base$class.sendRequest(Base.scala:131) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Base$class.getJSON(Base.scala:29) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at helpers.ServiceHelper$.getValueJson(ServiceHelper.scala:1802) [tpt_web.tpt_web-2.2.jar:2.2]
[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `ORA-00942: table or view does not exist
`
[error] application - Failed to get value of metric[oracle_io_stat] for mo[service_database][6744]
java.lang.RuntimeException: ORA-00942: table or view does not exist

    at lib.rest.Base$class.sendRequest(Base.scala:131) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Base$class.getJSON(Base.scala:29) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at helpers.ServiceHelper$.getValueJson(ServiceHelper.scala:1802) [tpt_web.tpt_web-2.2.jar:2.2]
[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `请求超时`
[error] application - Failed to get value of metric[oracle_sga_info] for mo[service_database][6744]
java.lang.RuntimeException: 请求超时
    at lib.rest.Base$class.sendRequest(Base.scala:131) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Base$class.getJSON(Base.scala:29) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at helpers.ServiceHelper$.getValueJson(ServiceHelper.scala:1802) [tpt_web.tpt_web-2.2.jar:2.2]
[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `ORA-00942: table or view does not exist
`
[error] application - Failed to get value of metric[oracle_sga_dynamic_components] for mo[service_database][6744]
java.lang.RuntimeException: ORA-00942: table or view does not exist

    at lib.rest.Base$class.sendRequest(Base.scala:131) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Base$class.getJSON(Base.scala:29) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at helpers.ServiceHelper$.getValueJson(ServiceHelper.scala:1802) [tpt_web.tpt_web-2.2.jar:2.2]
[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `'USE_DB_RECOVERY_FILE_DEST' is disabled.`
[error] application - Failed to get value of metric[oracle_archiver_stat] for mo[service_database][6644]
java.lang.RuntimeException: 'USE_DB_RECOVERY_FILE_DEST' is disabled.
    at lib.rest.Base$class.sendRequest(Base.scala:131) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Base$class.getJSON(Base.scala:29) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at helpers.ServiceHelper$.getValueJson(ServiceHelper.scala:1802) [tpt_web.tpt_web-2.2.jar:2.2]
[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `请求超时`
[error] application - Failed to get value of metric[oracle_hit_ratio] for mo[service_database][6744]
java.lang.RuntimeException: 请求超时
    at lib.rest.Base$class.sendRequest(Base.scala:131) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Base$class.getJSON(Base.scala:29) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at helpers.ServiceHelper$.getValueJson(ServiceHelper.scala:1802) [tpt_web.tpt_web-2.2.jar:2.2]
[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `ORA-00942: table or view does not exist
`
[error] application - Failed to get value of metric[oracle_io_stat] for mo[service_database][6744]
java.lang.RuntimeException: ORA-00942: table or view does not exist

    at lib.rest.Base$class.sendRequest(Base.scala:131) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Base$class.getJSON(Base.scala:29) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at helpers.ServiceHelper$.getValueJson(ServiceHelper.scala:1802) [tpt_web.tpt_web-2.2.jar:2.2]
[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `请求超时`
[error] application - Failed to get value of metric[oracle_process_count] for mo[service_database][6744]
java.lang.RuntimeException: 请求超时
    at lib.rest.Base$class.sendRequest(Base.scala:131) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Base$class.getJSON(Base.scala:29) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at helpers.ServiceHelper$.getValueJson(ServiceHelper.scala:1802) [tpt_web.tpt_web-2.2.jar:2.2]
```

注意：数据库取不到数据，客户非常关心，为重要事件！6月1日前需要解决！！！

**Comment by runner-mei** [comment]
日志文件呢

**Comment by runner-mei** [comment]
更换其它 连接方式看看， 不行让用户看看，是什么原因，因为慢说明不是我们的原因
http://www.cnblogs.com/phoebus0501/archive/2011/05/12/2044725.html

**Comment by Cuic** [comment]
更换一种链接方式驱动同样取数超时（OCI）@mei

**Comment by Cuic** [comment]
更还连接账号为SYSTEM数据可以正常取数
账号权限如下：

grant select on dba_tablespaces to imscj;
grant select on dba_free_space to imscj;
grant select on dba_data_files to imscj;
grant select on v_$sysstat to imscj;
grant select on v_$instance to imscj;
grant select on v_$sgainfo to imscj;
grant select on v_$librarycache to imscj;
grant select on v_$process to imscj;
grant select on v_$parameter to imscj;
grant select on v_$session to imscj;
grant select on v_$rowcache to imscj;
grant select on v_$pgastat to imscj;
grant select on v_$log to imscj;
grant select on v_$archived_log to imscj;
grant select on v_$flash_recovery_area_usage to imscj;
grant select on v_$buffer_pool_statistics to imscj;
grant select on v_$sgastat to imscj;
grant select on v_$flashback_database_logfile to imscj;
grant select on v_$pgastat to imscj;
grant select on v_$sqlarea to imscj;
grant select on dba_users to imscj;
grant select on v_$locked_object to imscj;
grant select on dba_objects to imscj;
grant select on v_$logfile to imscj;
grant select on sys.dba_jobs to imscj;
grant select on v_$sga to imscj;
grant select on v_$SYSMETRIC_SUMMARY to imscj;
grant select on v_$version to imscj;
grant select on v_$DATABASE to imscj;
grant select on all_users to imscj;
grant select on v_$datafile to imscj;
grant select on sys.ts$ to imscj;
grant select on v_$tempfile to imscj;
grant select on dba_segments to imscj;
grant select on v_$rollstat to imscj;
grant select on v_$rollname to imscj;
grant select on v_$filestat to imscj;
grant select on dba_temp_files to imscj;

**Comment by runner-mei** [comment]
现在怎么说？
