### ISSUE TITLE
[华东电力] HP-unix运行试图中虚拟内存没有数据

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#358]
HP-UNIX（SSH取数）
运行试图中虚拟内存没有显示；
虚拟内存的指标为：交换分区，在内存信息（Unix/Linux）不能获取数据。
URL获取数据使用swaps
打开运行HP-UNIX运行试图的web日志有如下错误：

```


[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `发生多个错误`
[error] application - Failed to get value of metric[disk_partition] for mo[service_host][3244]
java.lang.RuntimeException: 发生多个错误
    at lib.rest.Base$class.sendRequest(Base.scala:131) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Base$class.getJSON(Base.scala:29) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at helpers.ServiceHelper$.getValueJson(ServiceHelper.scala:1802) [tpt_web.tpt_web-2.2.jar:2.2]
[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `发生多个错误`
[error] application - Failed to get value of metric[cpuinfo] for mo[service_host][3244]
java.lang.RuntimeException: 发生多个错误
    at lib.rest.Base$class.sendRequest(Base.scala:131) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Base$class.getJSON(Base.scala:29) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at helpers.ServiceHelper$.getValueJson(ServiceHelper.scala:1802) [tpt_web.tpt_web-2.2.jar:2.2]
[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `read 'sys.oid' failed, 'snmp' is required.`
[error] application - Failed to get value of metric[hpunix_jobs] for mo[service_host][3244]
java.lang.RuntimeException: read 'sys.oid' failed, 'snmp' is required.
    at lib.rest.Base$class.sendRequest(Base.scala:131) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Base$class.getJSON(Base.scala:29) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at helpers.ServiceHelper$.getValueJson(ServiceHelper.scala:1802) [tpt_web.tpt_web-2.2.jar:2.2]
[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `发生多个错误`
[error] application - Failed to get value of metric[tcp_connection] for mo[service_host][3244]
java.lang.RuntimeException: 发生多个错误
    at lib.rest.Base$class.sendRequest(Base.scala:131) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Base$class.getJSON(Base.scala:29) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at helpers.ServiceHelper$.getValueJson(ServiceHelper.scala:1802) [tpt_web.tpt_web-2.2.jar:2.2]
[warn] application - Failed to get '[tcpConnState__descr=established].tcpConnState__descr.count' as int from null
[warn] application - Failed to get '[tcpConnState__descr=time_wait].tcpConnState__descr.count' as int from null
[warn] application - Failed to get '[tcpConnState__descr=close_wait].tcpConnState__descr.count' as int from null
[warn] application - Failed to get '[tcpConnState__descr=listen].tcpConnState__descr.count' as int from null
[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `发生多个错误`
[error] application - Failed to get value of metric[vmstat_rate] for mo[service_host][3244]
java.lang.RuntimeException: 发生多个错误
    at lib.rest.Base$class.sendRequest(Base.scala:131) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Base$class.getJSON(Base.scala:29) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at helpers.ServiceHelper$.getValueJson(ServiceHelper.scala:1802) [tpt_web.tpt_web-2.2.jar:2.2]
[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `发生多个错误`
[error] application - Failed to get value of metric[meminfo] for mo[service_host][3244]
java.lang.RuntimeException: 发生多个错误
    at lib.rest.Base$class.sendRequest(Base.scala:131) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Base$class.getJSON(Base.scala:29) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at helpers.ServiceHelper$.getValueJson(ServiceHelper.scala:1802) [tpt_web.tpt_web-2.2.jar:2.2]
[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `发生多个错误`
[error] application - Failed to get value of metric[vmstat_rate] for mo[service_host][3244]
java.lang.RuntimeException: 发生多个错误
    at lib.rest.Base$class.sendRequest(Base.scala:131) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Base$class.getJSON(Base.scala:29) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at helpers.ServiceHelper$.getValueJson(ServiceHelper.scala:1802) [tpt_web.tpt_web-2.2.jar:2.2]
[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `发生多个错误`
[error] application - Failed to get value of metric[iostat_rate] for mo[service_host][3244]
java.lang.RuntimeException: 发生多个错误
    at lib.rest.Base$class.sendRequest(Base.scala:131) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Base$class.getJSON(Base.scala:29) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at helpers.ServiceHelper$.getValueJson(ServiceHelper.scala:1802) [tpt_web.tpt_web-2.2.jar:2.2]
[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `发生多个错误`
[error] application - Failed to get value of metric[disk_partition] for mo[service_host][3244]
java.lang.RuntimeException: 发生多个错误
    at lib.rest.Base$class.sendRequest(Base.scala:131) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Base$class.getJSON(Base.scala:29) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at helpers.ServiceHelper$.getValueJson(ServiceHelper.scala:1802) [tpt_web.tpt_web-2.2.jar:2.2]
```

**Comment by runner-mei** [comment]
1. 日志文件呢
2. 用浏览器直接访问的结果呢

**Comment by xiauye** [comment]
https://coding.net/u/runner-mei/p/hw_issues/git/blob/master/scene_data/%E5%8D%8E%E4%B8%9C%E7%94%B5%E7%BD%91/logs.zip

**Comment by xiauye** [comment]
logs和URL取值都在里面
https://coding.net/u/runner-mei/p/hw_issues/git/blob/master/scene_data/%E5%8D%8E%E4%B8%9C%E7%94%B5%E7%BD%91/logs.zip
