### ISSUE TITLE
[华东电网] hp-unix磁盘信息获取不到

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#360]
系统：hp-unix
采数方式：ssh
问题：获取不到磁盘及文件系统信息。
**http://127.0.0.1:37072/objects_managed/3244/disk_partition**
internal error:
    read 'sys.oid' failed, 'snmp' is required.
    disk_partition_hp_unix: parse '/archlog1              (10.128.5.150:/archlog1) : 49156976 total allocated Kb
                                                  49077480 free allocated Kb
                                                     79496 used allocated Kb
                                                         1 % allocation used
/archlog2              (/dev/vg00/lvol4       ) : 49156944 total allocated Kb
                                                  49077960 free allocated Kb
                                                     78984 used allocated Kb
                                                         1 % allocation used
/home                  (/dev/vg00/lvol5       ) : 10404136 total allocated Kb
                                                  10381144 free allocated Kb
                                                     22992 used allocated Kb
                                                         1 % allocation used
/opt                   (/dev/vg00/lvol6       ) : 10444448 total allocated Kb
                                                   5256376 free allocated Kb
                                                   5188072 used allocated Kb
                                                        50 % allocation used
/oracle                (/dev/vg00/lvol7       ) : 49640619 total allocated Kb
                                                  41822756 free allocated Kb
                                                   7817863 used allocated Kb
                                                        16 % allocation used
/tmp                   (/dev/vg00/lvol8       ) : 20879048 total allocated Kb
                                                  11754848 free allocated Kb
                                                   9124200 used allocated Kb
                                                        44 % allocation used
/usr                   (/dev/vg00/lvol9       ) : 10428368 total allocated Kb
                                                   7297536 free allocated Kb
                                                   3130832 used allocated Kb
                                                        31 % allocation used
/var                   (/dev/vg00/lvol10      ) : 10472984 total allocated Kb
                                                   1751784 free allocated Kb
                                                   8721200 used allocated Kb
                                                        84 % allocation used
/stand                 (/dev/vg00/lvol1       ) : 10406712 total allocated Kb
                                                  10046928 free allocated Kb
                                                    359784 used allocated Kb
                                                         4 % allocation used
/                      (/dev/vg00/lvol3       ) : 10416192 total allocated Kb
                                                   8852000 free allocated Kb
                                                   1564192 used allocated Kb
                                                        16 % allocation used
' failed, sytex error.
    disk_partition_linux: Process exited with: 1. Reason was:  ()
    disk_partition_hr_windows: 'snmp' is required.

````
[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `发生多个错误`
[error] application - Failed to get value of metric[disk_partition] for mo[service_host][3244]
java.lang.RuntimeException: 发生多个错误
	at lib.rest.Base$class.sendRequest(Base.scala:131) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Base$class.getJSON(Base.scala:29) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at helpers.ServiceHelper$.getValueJson(ServiceHelper.scala:1802) [tpt_web.tpt_web-2.2.jar:2.2]
[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `发生多个错误`
[error] application - Failed to get value of metric[cpuinfo] for mo[service_host][3244]
java.lang.RuntimeException: 发生多个错误
	at lib.rest.Base$class.sendRequest(Base.scala:131) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Base$class.getJSON(Base.scala:29) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at helpers.ServiceHelper$.getValueJson(ServiceHelper.scala:1802) [tpt_web.tpt_web-2.2.jar:2.2]
[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `read 'sys.oid' failed, 'snmp' is required.`
[error] application - Failed to get value of metric[hpunix_jobs] for mo[service_host][3244]
java.lang.RuntimeException: read 'sys.oid' failed, 'snmp' is required.
	at lib.rest.Base$class.sendRequest(Base.scala:131) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Base$class.getJSON(Base.scala:29) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at helpers.ServiceHelper$.getValueJson(ServiceHelper.scala:1802) [tpt_web.tpt_web-2.2.jar:2.2]
[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `发生多个错误`
[error] application - Failed to get value of metric[tcp_connection] for mo[service_host][3244]
java.lang.RuntimeException: 发生多个错误
	at lib.rest.Base$class.sendRequest(Base.scala:131) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Base$class.getJSON(Base.scala:29) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at helpers.ServiceHelper$.getValueJson(ServiceHelper.scala:1802) [tpt_web.tpt_web-2.2.jar:2.2]
[warn] application - Failed to get '[tcpConnState__descr=established].tcpConnState__descr.count' as int from null
[warn] application - Failed to get '[tcpConnState__descr=time_wait].tcpConnState__descr.count' as int from null
[warn] application - Failed to get '[tcpConnState__descr=close_wait].tcpConnState__descr.count' as int from null
[warn] application - Failed to get '[tcpConnState__descr=listen].tcpConnState__descr.count' as int from null
[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `发生多个错误`
[error] application - Failed to get value of metric[vmstat_rate] for mo[service_host][3244]
java.lang.RuntimeException: 发生多个错误
	at lib.rest.Base$class.sendRequest(Base.scala:131) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Base$class.getJSON(Base.scala:29) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at helpers.ServiceHelper$.getValueJson(ServiceHelper.scala:1802) [tpt_web.tpt_web-2.2.jar:2.2]
[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `发生多个错误`
[error] application - Failed to get value of metric[meminfo] for mo[service_host][3244]
java.lang.RuntimeException: 发生多个错误
	at lib.rest.Base$class.sendRequest(Base.scala:131) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Base$class.getJSON(Base.scala:29) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at helpers.ServiceHelper$.getValueJson(ServiceHelper.scala:1802) [tpt_web.tpt_web-2.2.jar:2.2]
[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `发生多个错误`
[error] application - Failed to get value of metric[vmstat_rate] for mo[service_host][3244]
java.lang.RuntimeException: 发生多个错误
	at lib.rest.Base$class.sendRequest(Base.scala:131) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Base$class.getJSON(Base.scala:29) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at helpers.ServiceHelper$.getValueJson(ServiceHelper.scala:1802) [tpt_web.tpt_web-2.2.jar:2.2]
[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `发生多个错误`
[error] application - Failed to get value of metric[iostat_rate] for mo[service_host][3244]
java.lang.RuntimeException: 发生多个错误
	at lib.rest.Base$class.sendRequest(Base.scala:131) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Base$class.getJSON(Base.scala:29) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at helpers.ServiceHelper$.getValueJson(ServiceHelper.scala:1802) [tpt_web.tpt_web-2.2.jar:2.2]
[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `发生多个错误`
[error] application - Failed to get value of metric[disk_partition] for mo[service_host][3244]
java.lang.RuntimeException: 发生多个错误
	at lib.rest.Base$class.sendRequest(Base.scala:131) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Base$class.getJSON(Base.scala:29) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at helpers.ServiceHelper$.getValueJson(ServiceHelper.scala:1802) [tpt_web.tpt_web-2.2.jar:2.2]
````

**Comment by runner-mei** [comment]
fixed

**Comment by Cuic** [comment]
磁盘信息已经获取-closed
