### ISSUE TITLE
 Execution exception NullPointerException: null

### ISSUE THREAD

**Issue by runner-mei** [three-plus-three/hw_issues#363]
```
! @703i937oc - Internal server error, for (GET) [/hengwei/network_topologies/annotation?hide_tip=true&el_type=node&el_id=5236&random_ts=1462934468945&screen_width=1920&screen_height=1050] ->

play.api.Application$$anon$1: Execution exception[[NullPointerException: null]]
    at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.11.1.jar:na]
Caused by: java.lang.NullPointerException: null
    at scala.Predef$.Float2float(Predef.scala:359) ~[org.scala-lang.scala-library-2.11.1.jar:na]
    at helpers.TopologyHelper$$anonfun$resolveMemUsage$2.apply(TopologyHelper.scala:497) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at helpers.TopologyHelper$$anonfun$resolveMemUsage$2.apply(TopologyHelper.scala:496) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at scala.collection.immutable.List.foreach(List.scala:383) ~[org.scala-lang.scala-library-2.11.1.jar:na]
    at helpers.TopologyHelper$.resolveMemUsage(TopologyHelper.scala:496) ~[tpt_web.tpt_web-2.2.jar:2.2]
[error] application - Server exception happened
play.api.Application$$anon$1: Execution exception[[NullPointerException: null]]
    at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.11.1.jar:na]
Caused by: java.lang.NullPointerException: null
    at scala.Predef$.Float2float(Predef.scala:359) ~[org.scala-lang.scala-library-2.11.1.jar:na]
    at helpers.TopologyHelper$$anonfun$resolveMemUsage$2.apply(TopologyHelper.scala:497) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at helpers.TopologyHelper$$anonfun$resolveMemUsage$2.apply(TopologyHelper.scala:496) ~[tpt_web.tpt_web-2.2.jar:2.2]
    at scala.collection.immutable.List.foreach(List.scala:383) ~[org.scala-lang.scala-library-2.11.1.jar:na]
    at helpers.TopologyHelper$.resolveMemUsage(TopologyHelper.scala:496) ~[tpt_web.tpt_web-2.2.jar:2.2]
```

**Comment by eeiceyes** [comment]
fixed
