### ISSUE TITLE
[华东电网] NullPointerException

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#383]
web_server.log

```
play.api.Application$$anon$1: Execution exception[[RuntimeException: java.lang.NullPointerException]]
    at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.11.1.jar:na]
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
    at lib.rest.Base$class.sendRequest(Base.scala:131) ~[tpt_web.tpt_web-2.3.jar:2.3]
    at lib.rest.Base$class.getObjectArray(Base.scala:44) ~[tpt_web.tpt_web-2.3.jar:2.3]
    at lib.rest.TourInspectionRest$.getObjectArray(TourInspectionRest.scala:11) ~[tpt_web.tpt_web-2.3.jar:2.3]
    at lib.rest.TourInspectionRest$.allExpiredTasks(TourInspectionRest.scala:34) ~[tpt_web.tpt_web-2.3.jar:2.3]
    at controllers.TourInspectionController$$anonfun$indexTaskException$1.apply(TourInspectionController.scala:238) ~[tpt_web.tpt_web-2.3.jar:2.3]
[error] application - Server exception happened
play.api.Application$$anon$1: Execution exception[[RuntimeException: java.lang.NullPointerException]]
    at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.11.1.jar:na]
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
    at lib.rest.Base$class.sendRequest(Base.scala:131) ~[tpt_web.tpt_web-2.3.jar:2.3]
    at lib.rest.Base$class.getObjectArray(Base.scala:44) ~[tpt_web.tpt_web-2.3.jar:2.3]
    at lib.rest.TourInspectionRest$.getObjectArray(TourInspectionRest.scala:11) ~[tpt_web.tpt_web-2.3.jar:2.3]
    at lib.rest.TourInspectionRest$.allExpiredTasks(TourInspectionRest.scala:34) ~[tpt_web.tpt_web-2.3.jar:2.3]
    at controllers.TourInspectionController$$anonfun$indexTaskException$1.apply(TourInspectionController.scala:238) ~[tpt_web.tpt_web-2.3.jar:2.3]
```

server-biz.log

```
2016-06-17 16:07:38,321-[TS] INFO pool-7-thread-79 com.tpt.nm.biz.san_management.service.impl.SanTopologyListener - Received topology event
g.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:43)
    at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:67)
    at org.jboss.netty.handler.execution.OrderedMemoryAwareThreadPoolExecutor$ChildExecutor.run(OrderedMemoryAwareThreadPoolExecutor.java:314)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at com.tpt.nm.biz.tour_inspection.service.impl.InspectionManager.getExpiredTasks(InspectionManager.java:177)
    at com.tpt.nm.biz.rest.resources.tour_inspection.InspectTasksResource.getExpiredTasks(InspectTasksResource.java:206)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:137)
    ... 16 more
2016-06-17 15:36:56,386-[TS] ERROR pool-7-thread-76 com.tpt.nm.share.exception.RestApplicationExceptionMapper - ApplicationException was thrown!
org.jboss.resteasy.spi.ApplicationException: java.lang.NullPointerException
    at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:146)
    at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:280)
    at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:234)
    at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:221)
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:356)
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:179)
    at org.jboss.resteasy.plugins.server.netty.RequestDispatcher.service(RequestDispatcher.java:81)
    at org.jboss.resteasy.plugins.server.netty.RequestHandler.messageReceived(RequestHandler.java:56)
    at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
    at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
    at org.jboss.netty.handler.execution.ChannelUpstreamEventRunnable.doRun(ChannelUpstreamEventRunnable.java:43)
    at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:67)
    at org.jboss.netty.handler.execution.OrderedMemoryAwareThreadPoolExecutor$ChildExecutor.run(OrderedMemoryAwareThreadPoolExecutor.java:314)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at com.tpt.nm.biz.tour_inspection.service.impl.InspectionManager.getExpiredTasks(InspectionManager.java:177)
    at com.tpt.nm.biz.rest.resources.tour_inspection.InspectTasksResource.getExpiredTasks(InspectTasksResource.java:206)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:137)
    ... 16 more
2016-06-17 15:37:31,138-[TS] WARN RedisQueuemetrics_arrive com.tpt.nm.biz.m
```

**Comment by eeiceyes** [comment]
fixed
