### ISSUE TITLE
设备右键 - 取设备 arp 表报错

### ISSUE THREAD

**Issue by runner-mei** [three-plus-three/hw_issues#569]
````
[error] application - Server exception happened
play.api.Application$$anon$1: Execution exception[[JSONException: exepct '[', but EOF]]
	at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.11.1.jar:na]
Caused by: com.alibaba.fastjson.JSONException: exepct '[', but EOF
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:581) ~[com.alibaba.fastjson-1.2.4.jar:na]
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:571) ~[com.alibaba.fastjson-1.2.4.jar:na]
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:566) ~[com.alibaba.fastjson-1.2.4.jar:na]
	at com.alibaba.fastjson.JSON.parseArray(JSON.java:347) ~[com.alibaba.fastjson-1.2.4.jar:na]
	at lib.rest.Metrics$.getMetricList(Metrics.scala:15) ~[tpt_web.tpt_web-2.3.jar:2.3]
````

**Comment by runner-mei** [comment]
注意，返回结果为 null

**Comment by runner-mei** [comment]
已 fixed
