### ISSUE TITLE
自动刷新功能可能有问题， 在南华的发回来的文件中有大量的错误 “ 指定的线路已经不存在”， 可能原因是自动刷新导致线路被删除？

### ISSUE THREAD

**Issue by runner-mei** [three-plus-three/hw_issues#666]
自动刷新功能可能有问题， 在南华的发回来的文件中有大量的错误 “ 指定的线路已经不存在”， 可能原因是自动刷新导致线路被删除

````
[error] application - Server exception happened
play.api.Application$$anon$1: Execution exception[[RuntimeException: 指定的线路已经不存在！]]
	at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.11.1.jar:na]
Caused by: java.lang.RuntimeException: 指定的线路已经不存在！
	at lib.rest.Base$class.sendRequest(Base.scala:147) ~[tpt_web.tpt_web-2.3.jar:2.3]
	at lib.rest.Base$class.getObject(Base.scala:49) ~[tpt_web.tpt_web-2.3.jar:2.3]
	at lib.rest.Links$.getObject(Links.scala:9) ~[tpt_web.tpt_web-2.3.jar:2.3]
	at lib.rest.Links$.get(Links.scala:21) ~[tpt_web.tpt_web-2.3.jar:2.3]
	at views.html.report_management.view.flux_stat_origin$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$3.apply(flux_stat_origin.template.scala:36) ~[tpt_web.tpt_web-2.3.jar:2.3]
````

**Comment by eeiceyes** [comment]
fixed

**Comment by eeiceyes** [comment]
流量报表所关联的线路已经被删除，该法是忽略此类线路，不再报错
