### ISSUE TITLE
生产新的拓扑图时，生成失败

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#667]
IP网段设置如下
![image](https://cloud.githubusercontent.com/assets/20636259/18621889/cbabdd5c-7e5b-11e6-88a8-bc62b1e2228a.png)

错误提示：

```
![image](https://cloud.githubusercontent.com/assets/20636259/18621880/bc262d6a-7e5b-11e6-926c-f50451e1d610.png)


[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `java.lang.RuntimeException: Failed to get resource, Connect to 127.0.0.1:41574 [/127.0.0.1] failed: Connection refused: connect`
[error] play - Cannot invoke the action, eventually got an error: java.lang.RuntimeException: java.lang.RuntimeException: Failed to get resource, Connect to 127.0.0.1:41574 [/127.0.0.1] failed: Connection refused: connect
[error] application - 

! @71e953mmo - Internal server error, for (POST) [/hengwei/topologies/search_topology?is_append=false&random_ts=1474255353916&screen_width=1440&screen_height=856] ->

play.api.Application$$anon$1: Execution exception[[RuntimeException: java.lang.RuntimeException: Failed to get resource, Connect to 127.0.0.1:41574 [/127.0.0.1] failed: Connection refused: connect]]
    at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.11.1.jar:na]
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Failed to get resource, Connect to 127.0.0.1:41574 [/127.0.0.1] failed: Connection refused: connect
    at lib.rest.Base$class.sendRequest(Base.scala:150) ~[tpt_web.tpt_web-2.3.jar:2.3]
    at lib.rest.Base$class.postJson(Base.scala:60) ~[tpt_web.tpt_web-2.3.jar:2.3]
    at lib.rest.TopologyDiscovers$.postJson(TopologyDiscovers.scala:8) ~[tpt_web.tpt_web-2.3.jar:2.3]
    at lib.rest.TopologyDiscovers$.startDiscover(TopologyDiscovers.scala:17) ~[tpt_web.tpt_web-2.3.jar:2.3]
    at controllers.TopologyController$$anonfun$searchTopology$1$$anonfun$apply$5.apply(TopologyController.scala:82) ~[tpt_web.tpt_web-2.3.jar:2.3]
[error] application - Server exception happened
play.api.Application$$anon$1: Execution exception[[RuntimeException: java.lang.RuntimeException: Failed to get resource, Connect to 127.0.0.1:41574 [/127.0.0.1] failed: Connection refused: connect]]
    at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
    at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.11.1.jar:na]
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Failed to get resource, Connect to 127.0.0.1:41574 [/127.0.0.1] failed: Connection refused: connect
    at lib.rest.Base$class.sendRequest(Base.scala:150) ~[tpt_web.tpt_web-2.3.jar:2.3]
    at lib.rest.Base$class.postJson(Base.scala:60) ~[tpt_web.tpt_web-2.3.jar:2.3]
    at lib.rest.TopologyDiscovers$.postJson(TopologyDiscovers.scala:8) ~[tpt_web.tpt_web-2.3.jar:2.3]
    at lib.rest.TopologyDiscovers$.startDiscover(TopologyDiscovers.scala:17) ~[tpt_web.tpt_web-2.3.jar:2.3]
    at controllers.TopologyController$$anonfun$searchTopology$1$$anonfun$apply$5.apply(TopologyController.scala:82) ~[tpt_web.tpt_web-2.3.jar:2.3]
```

**Comment by eeiceyes** [comment]
fixed
