### ISSUE TITLE
错误消息乱码

### ISSUE THREAD

**Issue by runner-mei** [three-plus-three/hw_issues#67]
[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `姝ｅ湪閲囬泦涓?S205001.suggestion=璇ユ寚鏍囬渶瑕侀噰闆嗕袱娆★紝杩欐槸绗竴娆￠噰闆嗭紝璇风◢鍊欓噸鏂伴噰闆?`
[error] application - Failed to get value of `weblogic_jms_session_statistics_rate` from `service_midware`,`41649`
java.lang.RuntimeException: 姝ｅ湪閲囬泦涓?S205001.suggestion=璇ユ寚鏍囬渶瑕侀噰闆嗕袱娆★紝杩欐槸绗竴娆￠噰闆嗭紝璇风◢鍊欓噸鏂伴噰闆?
	at lib.rest.Base$class.sendRequest(Base.scala:129) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Base$class.getJSON(Base.scala:28) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at helpers.IndicatorHelper$.helpers$IndicatorHelper$$getMetricValue(IndicatorHelper.scala:40) [tpt_web.tpt_web-2.2.jar:2.2]
[error] play - Cannot invoke the action, eventually got an error: java.util.NoSuchElementException: key not found: req/s
[error] application -

**Comment by runner-mei** [comment]
已修复
