### ISSUE TITLE
在 linux 上启动时拷贝 resources 目录失败

### ISSUE THREAD

**Issue by runner-mei** [three-plus-three/hw_issues#838]
````

2016-11-12 14:04:47,547 - [DEBUG] - from application in main
Failed to migrate images
java.io.FileNotFoundException: resources (是一个目录)
        at java.io.FileInputStream.open0(Native Method) ~[na:1.8.0_111]
        at java.io.FileInputStream.open(FileInputStream.java:195) ~[na:1.8.0_111]
        at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[na:1.8.0_111]
        at com.google.common.io.Files$FileByteSource.openStream(Files.java:125) ~[com.google.guava.guava-18.0.jar:na]
        at com.google.common.io.Files$FileByteSource.openStream(Files.java:115) ~[com.google.guava.guava-18.0.jar:na]
        at com.google.common.io.ByteSource.copyTo(ByteSource.java:239) ~[com.google.guava.guava-18.0.jar:na]
        at com.google.common.io.Files.copy(Files.java:305) ~[com.google.guava.guava-18.0.jar:na]
        at com.google.common.io.Files.move(Files.java:490) ~[com.google.guava.guava-18.0.jar:na]
        at lib.Global$.onStart(Global.scala:136) ~[tpt_web.tpt_web-2.3.jar:2.3]
        at play.api.GlobalPlugin.onStart(GlobalSettings.scala:220) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
        at scala.collection.immutable.List.foreach(List.scala:383) [org.scala-lang.scala-library-2.11.1.jar:na]
        at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
        at play.api.Play$.start(Play.scala:90) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
        at play.core.StaticApplication.<init>(ApplicationProvider.scala:55) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
        at play.core.server.NettyServer$.createServer(NettyServer.scala:253) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:289) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:284) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
        at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.11.1.jar:na]
        at play.core.server.NettyServer$.main(NettyServer.scala:284) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
        at play.core.server.NettyServer.main(NettyServer.scala) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]

````

**Comment by runner-mei** [comment]
改成安装时安装脚本自动拷贝
