### ISSUE TITLE
短信服务器设置

### ISSUE THREAD

**Issue by RasAlGu1** [three-plus-three/hw_issues#858]
![image](https://cloud.githubusercontent.com/assets/20636259/20469928/e5e135c8-afde-11e6-86ee-fbb0cd36a536.png)

**Comment by runner-mei** [comment]
fix

**Comment by RasAlGu1** [comment]
点击确定时，提示
![image](https://cloud.githubusercontent.com/assets/20636259/23637683/13e22e28-0318-11e7-866c-69d2213bf830.png)

**Comment by runner-mei** [comment]
这个文件现在有了， 但是在你拷贝时出错了
Caused by: java.io.IOException: 没有那个文件或目录
	at java.io.UnixFileSystem.createFileExclusively(Native Method) ~[na:1.8.0_111]
	at java.io.File.createNewFile(File.java:1012) ~[na:1.8.0_111]
	at controllers.SystemController$$anonfun$saveSMSSet$1.apply(SystemController.scala:289) ~[tpt_web.tpt_web-2.3.jar:2.3]
	at controllers.SystemController$$anonfun$saveSMSSet$1.apply(SystemController.scala:264) ~[tpt_web.tpt_web-2.3.jar:2.3]
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:433) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:432) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.mvc.Action$.invokeBlock(Action.scala:556) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.mvc.Action$.invokeBlock(Action.scala:555) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:518) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.11.1.jar:na]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483) ~[com.typesafe.play.play-iteratees_2.11-2.3.9.jar:2.3.9]
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483) ~[com.typesafe.play.play-iteratees_2.11-2.3.9.jar:2.3.9]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519) ~[com.typesafe.play.play-iteratees_2.11-2.3.9.jar:2.3.9]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519) ~[com.typesafe.play.play-iteratees_2.11-2.3.9.jar:2.3.9]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496) ~[com.typesafe.play.play-iteratees_2.11-2.3.9.jar:2.3.9]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496) ~[com.typesafe.play.play-iteratees_2.11-2.3.9.jar:2.3.9]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[org.scala-lang.scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[org.scala-lang.scala-library-2.11.1.jar:na]
	... 6 common frames omitted

**Comment by eeiceyes** [comment]
这个问题还存在吗？

**Comment by hengwei-test** [comment]
hengwei_setup_3.2.20170922_2764_x64.exe  版本确认，close处理。
