### ISSUE TITLE
告警指标参数配置加载失败

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#91]
告警规则指标列表中(主机) ，"文件信息">"最后更新时间">数据所以行  出现报错 （报错信息:加载失败：发生多个错误

报错日志如下：
[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `发生多个错误`
[error] play - Cannot invoke the action, eventually got an error: java.lang.RuntimeException: 发生多个错误
[error] application - 

! @6ocgiglmo - Internal server error, for (GET) [/hengwei/kpi_values/lines?managed_type=service_host&category=linux&mo_id=57&kpi_name=ls&metric=ls&attribute=last_modified&random_ts=1449631453677&screen_width=1366&screen_height=738] ->

play.api.Application$$anon$1: Execution exception[[RuntimeException: 发生多个错误]]
	at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.11.1.jar:na]
Caused by: java.lang.RuntimeException: 发生多个错误
	at lib.rest.Base$class.sendRequest(Base.scala:129) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Base$class.getJSON(Base.scala:28) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at controllers.KpiController$$anonfun$linesForTableMetric$1.apply(KpiController.scala:141) ~[tpt_web.tpt_web-2.2.jar:2.2]
[error] application - Server exception happened
play.api.Application$$anon$1: Execution exception[[RuntimeException: 发生多个错误]]
	at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.11.1.jar:na]
Caused by: java.lang.RuntimeException: 发生多个错误
	at lib.rest.Base$class.sendRequest(Base.scala:129) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Base$class.getJSON(Base.scala:28) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Metrics$.getJSON(Metrics.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Metrics$.getMetricValue(Metrics.scala:23) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at controllers.KpiController$$anonfun$linesForTableMetric$1.apply(KpiController.scala:141) ~[tpt_web.tpt_web-2.2.jar:2.2]

**Comment by eeiceyes** [comment]
fixed
