### ISSUE TITLE
设备迁移 执行操作失败

### ISSUE THREAD

**Issue by Cuic** [three-plus-three/hw_issues#94]
根图中 右键 设备迁移 执行操作失败

[error] application - Get `HTTP/1.1 500 Internal Server Error` from rest server, errors => `{"errorCode": 100001, "errorMessage": "Unknown Exception"}`
[error] play - Cannot invoke the action, eventually got an error: java.lang.RuntimeException: 未知错误导致操作失败！
[error] application - 

! @6ocnm4h59 - Internal server error, for (PUT) [/hengwei/network_topologies/update_managed_ip?el_id=897&random_ts=1449716239259&screen_width=1366&screen_height=738] ->

play.api.Application$$anon$1: Execution exception[[RuntimeException: 未知错误导致操作失败！]]
	at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.11.1.jar:na]
Caused by: java.lang.RuntimeException: 未知错误导致操作失败！
	at lib.rest.Base$class.sendRequest(Base.scala:127) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Base$class.putJson(Base.scala:77) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Devices$.putJson(Devices.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Devices$.updateAddress(Devices.scala:114) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at controllers.NetworkTopologyController$$anonfun$updateManagedIp$1.apply(NetworkTopologyController.scala:547) ~[tpt_web.tpt_web-2.2.jar:2.2]
[error] application - Server exception happened
play.api.Application$$anon$1: Execution exception[[RuntimeException: 未知错误导致操作失败！]]
	at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.9.jar:2.3.9]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.11.1.jar:na]
Caused by: java.lang.RuntimeException: 未知错误导致操作失败！
	at lib.rest.Base$class.sendRequest(Base.scala:127) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Base$class.putJson(Base.scala:77) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Devices$.putJson(Devices.scala:12) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at lib.rest.Devices$.updateAddress(Devices.scala:114) ~[tpt_web.tpt_web-2.2.jar:2.2]
	at controllers.NetworkTopologyController$$anonfun$updateManagedIp$1.apply(NetworkTopologyController.scala:547) ~[tpt_web.tpt_web-2.2.jar:2.2]

**Comment by eeiceyes** [comment]
fixed
